# sciences po

## récupération des chercheurs

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

headers = {"User-Agent": "Mozilla/5.0"}

urls = [
    "https://www.sciencespo.fr/department-economics/people/permanent-faculty/",
    "https://www.sciencespo.fr/department-economics/people/permanent-faculty/1/"
]

data = []

for url in urls:

    response = requests.get(url, headers=headers)
    response.encoding = "utf-8"
    html = response.text

    soup = BeautifulSoup(html, "html.parser")

    cards = soup.find_all("div", class_="research-item-module--researcherCardList--a9250")

    for card in cards:

        name_tag = card.find("h3")
        title_tag = card.find("p", class_="research-item-module--title--094b0")

        name = name_tag.get_text(" ", strip=True) if name_tag else None
        title = title_tag.get_text(" ", strip=True) if title_tag else None

        # récupérer les research interests
        interests = None
        interest_block = card.find("p", class_="research-item-module--containerAll--8bb35")

        if interest_block:
            spans = interest_block.find_all("span")
            if len(spans) > 1:
                interests = spans[1].get_text(" ", strip=True)

        data.append({
            "name": name,
            "title_raw": title,
            "research_interests": interests
        })

df = pd.DataFrame(data)

print(df)

                        name  \
0                 Yann Algan
1          Facundo Argañaraz
2            Ghazala Azmat †
3             Johannes Boehm
4             Paul Bouscasse
5                 Julia Cagé
6               Pierre Cahuc
7             Giulia Caprini
8        Nicolas Coeurdacier
9     Pierre-Philippe Combes
10           Jeanne Commault
11   Clément De Chaisemartin
12             Antoine Ferey
13           Axelle Ferriere
14          Roberto Galbiati
15          Stéphane Guibaud
16             Sergei Guriev
17          Jeanne Hagenbach
18                 Junnan He
19              Emeric Henry
20           Kerstin Holzheu
21            Clément Imbert
22           Suzanna Khalifa
23        Justine Knebelmann
24             Marleen Marra
25             Thierry Mayer
26           Isabelle Mejean
27         Claire Montialoux
28  Kevin Hjortshøj O'Rourke
29            Franz Ostrizek
30      Eduardo Perez-Richet
31         Guillaume Plantin
32          Stefan Pollinger
33              Xavier Ragot
34           Morgane Richard
35           Jean-Marc Robin
36          Clara Santamaria
37         Moritz Schularick
38               Jack Willis

                                            title_raw  \
0                                           Professor
1                                 Assistant Professor
2                                           Professor
3                 Associate Professor (on secondment)
4                                 Assistant Professor
5                                           Professor
6                                           Professor
7                                 Assistant Professor
8                                           Professor
9   CNRS Research Professor , Head of doctoral stu...
10                                Assistant Professor
11                                          Professor
12                                Assistant Professor
13                                     CNRS Professor
14                            CNRS Research Professor
15                                          Professor
16                          Professor (on secondment)
17                            CNRS Research Professor
18                Assistant Professor (on secondment)
19    Professor , Head of the Department of Economics
20                                Assistant Professor
21                                          Professor
22                                Assistant Professor
23                                Assistant Professor
24                Assistant Professor (on secondment)
25                                          Professor
26                                          Professor
27                                Assistant Professor
28                            CNRS Research Professor
29                                Assistant Professor
30                                          Professor
31                                          Professor
32                Assistant Professor (on secondment)
33            CNRS Research Professor , OFCE Chairman
34                                Assistant Professor
35                                          Professor
36                                Assistant Professor
37                                          Professor
38                                          Professor

                                   research_interests
0   Public Economics; Cultural Economics; Social I...
1   Econometrics; Causal Inference; Semiparametric...
2   Labour Economics; Public Economics; Gender Eco...
3   Macroeconomics; International Trade; Industria...
4   Macroeconomics; Monetary Economics; Internatio...
5   Democracy; Information Economics; Political Ec...
6        Unemployment, Macroeconomics, Labour Markets
7   Political Economy; Health Economics; Behaviour...
8   International Macroeconomics and Finance, Macr...
9   International TradeEconomic GeographyCities an...
10  Macroeconomics, Applied microeconomics, Househ...
11               Economics of education, Econometrics
12                      Political Economy, Tax System
13  Cycle; Income and Wealth Inequality; Internati...
14  Political Economy; Applied Economics; Law and ...
15  Asset Pricing, International Finance, Dynamic ...
16  Political Economy, Development Economics, Labo...
17  Game theory, Microeconomic Theory, Experimenta...
18  Econometrics and decision theory, Model sparsi...
19  Economics of Innovation, Industrial Organizati...
20  Labor economics, Industrial Organisation Econo...
21  Development Economics, Labour Market and Econo...
22  Applied microeconomics, Culture, Development E...
23             State capacity in developing countries
24  Game theory, Econometric models, Behaviour of ...
25  International trade, Economic geography, Multi...
26             International Macroeconomics and Trade
27  Labour Market and Economics, Inequality and Di...
28           Economic History, International Economic
29  Behavioral Economics, Industrial Organisation ...
30  Microeconomic Theory; Game Theory; Political E...
31                   Monetary and Financial Economics
32  Public Economics, Applied Econometrics, and En...
33  Macroeconomics, Incomplete Markets, theory and...
34  Macroeconomics; Spatial Economics; Household F...
35       Labour markets, Econometrics, Microeconomics
36  spatial economics, macro, and labor, with a pa...
37  Macrofinance, Banking and financial stability,...
38  Development Economics; Behavioural & Experimen...

In [2]:
df

,name,title_raw,research_interests
0,Yann Algan,Professor,Public Economics; Cultural Economics; Social I...
1,Facundo Argañaraz,Assistant Professor,Econometrics; Causal Inference; Semiparametric...
2,Ghazala Azmat †,Professor,Labour Economics; Public Economics; Gender Eco...
3,Johannes Boehm,Associate Professor (on secondment),Macroeconomics; International Trade; Industria...
4,Paul Bouscasse,Assistant Professor,Macroeconomics; Monetary Economics; Internatio...
5,Julia Cagé,Professor,Democracy; Information Economics; Political Ec...
6,Pierre Cahuc,Professor,"Unemployment, Macroeconomics, Labour Markets"
7,Giulia Caprini,Assistant Professor,Political Economy; Health Economics; Behaviour...
8,Nicolas Coeurdacier,Professor,"International Macroeconomics and Finance, Macr..."
9,Pierre-Philippe Combes,"CNRS Research Professor , Head of doctoral stu...",International TradeEconomic GeographyCities an...
10,Jeanne Commault,Assistant Professor,"Macroeconomics, Applied microeconomics, Househ..."
11,Clément De Chaisemartin,Professor,"Economics of education, Econometrics"
12,Antoine Ferey,Assistant Professor,"Political Economy, Tax System"
13,Axelle Ferriere,CNRS Professor,Cycle; Income and Wealth Inequality; Internati...
14,Roberto Galbiati,CNRS Research Professor,Political Economy; Applied Economics; Law and ...
15,Stéphane Guibaud,Professor,"Asset Pricing, International Finance, Dynamic ..."
16,Sergei Guriev,Professor (on secondment),"Political Economy, Development Economics, Labo..."
17,Jeanne Hagenbach,CNRS Research Professor,"Game theory, Microeconomic Theory, Experimenta..."
18,Junnan He,Assistant Professor (on secondment),"Econometrics and decision theory, Model sparsi..."
19,Emeric Henry,"Professor , Head of the Department of Economics","Economics of Innovation, Industrial Organizati..."
20,Kerstin Holzheu,Assistant Professor,"Labor economics, Industrial Organisation Econo..."
21,Clément Imbert,Professor,"Development Economics, Labour Market and Econo..."
22,Suzanna Khalifa,Assistant Professor,"Applied microeconomics, Culture, Development E..."
23,Justine Knebelmann,Assistant Professor,State capacity in developing countries
24,Marleen Marra,Assistant Professor (on secondment),"Game theory, Econometric models, Behaviour of ..."
25,Thierry Mayer,Professor,"International trade, Economic geography, Multi..."
26,Isabelle Mejean,Professor,International Macroeconomics and Trade
27,Claire Montialoux,Assistant Professor,"Labour Market and Economics, Inequality and Di..."
28,Kevin Hjortshøj O'Rourke,CNRS Research Professor,"Economic History, International Economic"
29,Franz Ostrizek,Assistant Professor,"Behavioral Economics, Industrial Organisation ..."
30,Eduardo Perez-Richet,Professor,Microeconomic Theory; Game Theory; Political E...
31,Guillaume Plantin,Professor,Monetary and Financial Economics
32,Stefan Pollinger,Assistant Professor (on secondment),"Public Economics, Applied Econometrics, and En..."
33,Xavier Ragot,"CNRS Research Professor , OFCE Chairman","Macroeconomics, Incomplete Markets, theory and..."
34,Morgane Richard,Assistant Professor,Macroeconomics; Spatial Economics; Household F...
35,Jean-Marc Robin,Professor,"Labour markets, Econometrics, Microeconomics"
36,Clara Santamaria,Assistant Professor,"spatial economics, macro, and labor, with a pa..."
37,Moritz Schularick,Professor,"Macrofinance, Banking and financial stability,..."
38,Jack Willis,Professor,Development Economics; Behavioural & Experimen...

In [3]:
df["title_raw"].value_counts()

title_raw
Professor                                                          15
Assistant Professor                                                12
CNRS Research Professor                                             3
Assistant Professor (on secondment)                                 3
CNRS Research Professor , Head of doctoral studies in Economics     1
Associate Professor (on secondment)                                 1
CNRS Professor                                                      1
Professor (on secondment)                                           1
Professor , Head of the Department of Economics                     1
CNRS Research Professor , OFCE Chairman                             1
Name: count, dtype: int64

# création de la classifcation et du rang

In [4]:
def classify_position(title):

    t = title.lower()

    # Assistant Professor
    if "assistant professor" in t:
        return "Assistant Professor", "B"

    # Associate Professor
    if "associate professor" in t:
        return "Associate Professor", "A"

    # CNRS (à traiter plus tard)
    if "cnrs" in t:
        return "CNRS", None

    # Professor (mais pas assistant/associate)
    if "professor" in t:
        return "Full Professor", "A"

    return "Other", None

In [5]:
df[["profession", "rang"]] = df["title_raw"].apply(
    lambda x: pd.Series(classify_position(x))
)

In [6]:
df

,name,title_raw,research_interests,profession,rang
0,Yann Algan,Professor,Public Economics; Cultural Economics; Social I...,Full Professor,A
1,Facundo Argañaraz,Assistant Professor,Econometrics; Causal Inference; Semiparametric...,Assistant Professor,B
2,Ghazala Azmat †,Professor,Labour Economics; Public Economics; Gender Eco...,Full Professor,A
3,Johannes Boehm,Associate Professor (on secondment),Macroeconomics; International Trade; Industria...,Associate Professor,A
4,Paul Bouscasse,Assistant Professor,Macroeconomics; Monetary Economics; Internatio...,Assistant Professor,B
5,Julia Cagé,Professor,Democracy; Information Economics; Political Ec...,Full Professor,A
6,Pierre Cahuc,Professor,"Unemployment, Macroeconomics, Labour Markets",Full Professor,A
7,Giulia Caprini,Assistant Professor,Political Economy; Health Economics; Behaviour...,Assistant Professor,B
8,Nicolas Coeurdacier,Professor,"International Macroeconomics and Finance, Macr...",Full Professor,A
9,Pierre-Philippe Combes,"CNRS Research Professor , Head of doctoral stu...",International TradeEconomic GeographyCities an...,CNRS,None
10,Jeanne Commault,Assistant Professor,"Macroeconomics, Applied microeconomics, Househ...",Assistant Professor,B
11,Clément De Chaisemartin,Professor,"Economics of education, Econometrics",Full Professor,A
12,Antoine Ferey,Assistant Professor,"Political Economy, Tax System",Assistant Professor,B
13,Axelle Ferriere,CNRS Professor,Cycle; Income and Wealth Inequality; Internati...,CNRS,None
14,Roberto Galbiati,CNRS Research Professor,Political Economy; Applied Economics; Law and ...,CNRS,None
15,Stéphane Guibaud,Professor,"Asset Pricing, International Finance, Dynamic ...",Full Professor,A
16,Sergei Guriev,Professor (on secondment),"Political Economy, Development Economics, Labo...",Full Professor,A
17,Jeanne Hagenbach,CNRS Research Professor,"Game theory, Microeconomic Theory, Experimenta...",CNRS,None
18,Junnan He,Assistant Professor (on secondment),"Econometrics and decision theory, Model sparsi...",Assistant Professor,B
19,Emeric Henry,"Professor , Head of the Department of Economics","Economics of Innovation, Industrial Organizati...",Full Professor,A
20,Kerstin Holzheu,Assistant Professor,"Labor economics, Industrial Organisation Econo...",Assistant Professor,B
21,Clément Imbert,Professor,"Development Economics, Labour Market and Econo...",Full Professor,A
22,Suzanna Khalifa,Assistant Professor,"Applied microeconomics, Culture, Development E...",Assistant Professor,B
23,Justine Knebelmann,Assistant Professor,State capacity in developing countries,Assistant Professor,B
24,Marleen Marra,Assistant Professor (on secondment),"Game theory, Econometric models, Behaviour of ...",Assistant Professor,B
25,Thierry Mayer,Professor,"International trade, Economic geography, Multi...",Full Professor,A
26,Isabelle Mejean,Professor,International Macroeconomics and Trade,Full Professor,A
27,Claire Montialoux,Assistant Professor,"Labour Market and Economics, Inequality and Di...",Assistant Professor,B
28,Kevin Hjortshøj O'Rourke,CNRS Research Professor,"Economic History, International Economic",CNRS,None
29,Franz Ostrizek,Assistant Professor,"Behavioral Economics, Industrial Organisation ...",Assistant Professor,B
30,Eduardo Perez-Richet,Professor,Microeconomic Theory; Game Theory; Political E...,Full Professor,A
31,Guillaume Plantin,Professor,Monetary and Financial Economics,Full Professor,A
32,Stefan Pollinger,Assistant Professor (on secondment),"Public Economics, Applied Econometrics, and En...",Assistant Professor,B
33,Xavier Ragot,"CNRS Research Professor , OFCE Chairman","Macroeconomics, Incomplete Markets, theory and...",CNRS,None
34,Morgane Richard,Assistant Professor,Macroeconomics; Spatial Economics; Household F...,Assistant Professor,B
35,Jean-Marc Robin,Professor,"Labour markets, Econometrics, Microeconomics",Full Professor,A
36,Clara Santamaria,Assistant Professor,"spatial economics, macro, and labor, with a pa...",Assistant Professor,B
37,Moritz Schularick,Professor,"Macrofinance, Banking and financial stability,...",Full Professor,A
38,Jack Willis,Professor,Development Economics; Behavioural & Experimen...,Full Professor,A

## traitement des chercheurs cnrs dénommés 'CNRS Research Professor':

In [7]:
pip install unidecode

Requirement already satisfied: unidecode in /opt/python/lib/python3.13/site-packages (1.4.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import unidecode
import re

def build_profile_url(name):

    parts = name.lower().split()

    first = parts[0]
    last = parts[-1]

    # enlever accents
    first = unidecode.unidecode(first)
    last = unidecode.unidecode(last)

    # remplacer apostrophes par tiret
    last = last.replace("'", "-")

    # enlever autres caractères spéciaux
    first = re.sub(r"[^a-z\-]", "", first)
    last = re.sub(r"[^a-z\-]", "", last)

    slug = f"{last}-{first}"

    url = f"https://www.sciencespo.fr/department-economics/directory/{slug}/"

    return url

In [9]:
def classify_cnrs_page(url):

    headers = {"User-Agent": "Mozilla/5.0"}

    try:
        response = requests.get(url, headers=headers)
        response.encoding = "utf-8"

        soup = BeautifulSoup(response.text, "html.parser")

        bio = soup.find("div", class_="ckContent")

        text = bio.get_text(" ", strip=True).lower()

        if "director" in text or "directeur de recherche" in text or "(dr)" in text:
            return "DR CNRS", "A"

        elif "cnrs" in text:
            return "CR CNRS", "B"

        else:
            return "CNRS", None

    except:
        return "CNRS", None

In [10]:
for i, row in df.iterrows():

    if "cnrs" in row["title_raw"].lower():

        url = build_profile_url(row["name"])

        profession, rang = classify_cnrs_page(url)

        df.loc[i, "profession"] = profession
        df.loc[i, "rang"] = rang

In [11]:
df

,name,title_raw,research_interests,profession,rang
0,Yann Algan,Professor,Public Economics; Cultural Economics; Social I...,Full Professor,A
1,Facundo Argañaraz,Assistant Professor,Econometrics; Causal Inference; Semiparametric...,Assistant Professor,B
2,Ghazala Azmat †,Professor,Labour Economics; Public Economics; Gender Eco...,Full Professor,A
3,Johannes Boehm,Associate Professor (on secondment),Macroeconomics; International Trade; Industria...,Associate Professor,A
4,Paul Bouscasse,Assistant Professor,Macroeconomics; Monetary Economics; Internatio...,Assistant Professor,B
5,Julia Cagé,Professor,Democracy; Information Economics; Political Ec...,Full Professor,A
6,Pierre Cahuc,Professor,"Unemployment, Macroeconomics, Labour Markets",Full Professor,A
7,Giulia Caprini,Assistant Professor,Political Economy; Health Economics; Behaviour...,Assistant Professor,B
8,Nicolas Coeurdacier,Professor,"International Macroeconomics and Finance, Macr...",Full Professor,A
9,Pierre-Philippe Combes,"CNRS Research Professor , Head of doctoral stu...",International TradeEconomic GeographyCities an...,DR CNRS,A
10,Jeanne Commault,Assistant Professor,"Macroeconomics, Applied microeconomics, Househ...",Assistant Professor,B
11,Clément De Chaisemartin,Professor,"Economics of education, Econometrics",Full Professor,A
12,Antoine Ferey,Assistant Professor,"Political Economy, Tax System",Assistant Professor,B
13,Axelle Ferriere,CNRS Professor,Cycle; Income and Wealth Inequality; Internati...,CR CNRS,B
14,Roberto Galbiati,CNRS Research Professor,Political Economy; Applied Economics; Law and ...,DR CNRS,A
15,Stéphane Guibaud,Professor,"Asset Pricing, International Finance, Dynamic ...",Full Professor,A
16,Sergei Guriev,Professor (on secondment),"Political Economy, Development Economics, Labo...",Full Professor,A
17,Jeanne Hagenbach,CNRS Research Professor,"Game theory, Microeconomic Theory, Experimenta...",DR CNRS,A
18,Junnan He,Assistant Professor (on secondment),"Econometrics and decision theory, Model sparsi...",Assistant Professor,B
19,Emeric Henry,"Professor , Head of the Department of Economics","Economics of Innovation, Industrial Organizati...",Full Professor,A
20,Kerstin Holzheu,Assistant Professor,"Labor economics, Industrial Organisation Econo...",Assistant Professor,B
21,Clément Imbert,Professor,"Development Economics, Labour Market and Econo...",Full Professor,A
22,Suzanna Khalifa,Assistant Professor,"Applied microeconomics, Culture, Development E...",Assistant Professor,B
23,Justine Knebelmann,Assistant Professor,State capacity in developing countries,Assistant Professor,B
24,Marleen Marra,Assistant Professor (on secondment),"Game theory, Econometric models, Behaviour of ...",Assistant Professor,B
25,Thierry Mayer,Professor,"International trade, Economic geography, Multi...",Full Professor,A
26,Isabelle Mejean,Professor,International Macroeconomics and Trade,Full Professor,A
27,Claire Montialoux,Assistant Professor,"Labour Market and Economics, Inequality and Di...",Assistant Professor,B
28,Kevin Hjortshøj O'Rourke,CNRS Research Professor,"Economic History, International Economic",DR CNRS,A
29,Franz Ostrizek,Assistant Professor,"Behavioral Economics, Industrial Organisation ...",Assistant Professor,B
30,Eduardo Perez-Richet,Professor,Microeconomic Theory; Game Theory; Political E...,Full Professor,A
31,Guillaume Plantin,Professor,Monetary and Financial Economics,Full Professor,A
32,Stefan Pollinger,Assistant Professor (on secondment),"Public Economics, Applied Econometrics, and En...",Assistant Professor,B
33,Xavier Ragot,"CNRS Research Professor , OFCE Chairman","Macroeconomics, Incomplete Markets, theory and...",DR CNRS,A
34,Morgane Richard,Assistant Professor,Macroeconomics; Spatial Economics; Household F...,Assistant Professor,B
35,Jean-Marc Robin,Professor,"Labour markets, Econometrics, Microeconomics",Full Professor,A
36,Clara Santamaria,Assistant Professor,"spatial economics, macro, and labor, with a pa...",Assistant Professor,B
37,Moritz Schularick,Professor,"Macrofinance, Banking and financial stability,...",Full Professor,A
38,Jack Willis,Professor,Development Economics; Behavioural & Experimen...,Full Professor,A

In [12]:
df_sciencespo = df

In [13]:
df_sciencespo = df_sciencespo.rename(columns={"title_raw": "appelation_sur_site"})

In [14]:
df_sciencespo

,name,appelation_sur_site,research_interests,profession,rang
0,Yann Algan,Professor,Public Economics; Cultural Economics; Social I...,Full Professor,A
1,Facundo Argañaraz,Assistant Professor,Econometrics; Causal Inference; Semiparametric...,Assistant Professor,B
2,Ghazala Azmat †,Professor,Labour Economics; Public Economics; Gender Eco...,Full Professor,A
3,Johannes Boehm,Associate Professor (on secondment),Macroeconomics; International Trade; Industria...,Associate Professor,A
4,Paul Bouscasse,Assistant Professor,Macroeconomics; Monetary Economics; Internatio...,Assistant Professor,B
5,Julia Cagé,Professor,Democracy; Information Economics; Political Ec...,Full Professor,A
6,Pierre Cahuc,Professor,"Unemployment, Macroeconomics, Labour Markets",Full Professor,A
7,Giulia Caprini,Assistant Professor,Political Economy; Health Economics; Behaviour...,Assistant Professor,B
8,Nicolas Coeurdacier,Professor,"International Macroeconomics and Finance, Macr...",Full Professor,A
9,Pierre-Philippe Combes,"CNRS Research Professor , Head of doctoral stu...",International TradeEconomic GeographyCities an...,DR CNRS,A
10,Jeanne Commault,Assistant Professor,"Macroeconomics, Applied microeconomics, Househ...",Assistant Professor,B
11,Clément De Chaisemartin,Professor,"Economics of education, Econometrics",Full Professor,A
12,Antoine Ferey,Assistant Professor,"Political Economy, Tax System",Assistant Professor,B
13,Axelle Ferriere,CNRS Professor,Cycle; Income and Wealth Inequality; Internati...,CR CNRS,B
14,Roberto Galbiati,CNRS Research Professor,Political Economy; Applied Economics; Law and ...,DR CNRS,A
15,Stéphane Guibaud,Professor,"Asset Pricing, International Finance, Dynamic ...",Full Professor,A
16,Sergei Guriev,Professor (on secondment),"Political Economy, Development Economics, Labo...",Full Professor,A
17,Jeanne Hagenbach,CNRS Research Professor,"Game theory, Microeconomic Theory, Experimenta...",DR CNRS,A
18,Junnan He,Assistant Professor (on secondment),"Econometrics and decision theory, Model sparsi...",Assistant Professor,B
19,Emeric Henry,"Professor , Head of the Department of Economics","Economics of Innovation, Industrial Organizati...",Full Professor,A
20,Kerstin Holzheu,Assistant Professor,"Labor economics, Industrial Organisation Econo...",Assistant Professor,B
21,Clément Imbert,Professor,"Development Economics, Labour Market and Econo...",Full Professor,A
22,Suzanna Khalifa,Assistant Professor,"Applied microeconomics, Culture, Development E...",Assistant Professor,B
23,Justine Knebelmann,Assistant Professor,State capacity in developing countries,Assistant Professor,B
24,Marleen Marra,Assistant Professor (on secondment),"Game theory, Econometric models, Behaviour of ...",Assistant Professor,B
25,Thierry Mayer,Professor,"International trade, Economic geography, Multi...",Full Professor,A
26,Isabelle Mejean,Professor,International Macroeconomics and Trade,Full Professor,A
27,Claire Montialoux,Assistant Professor,"Labour Market and Economics, Inequality and Di...",Assistant Professor,B
28,Kevin Hjortshøj O'Rourke,CNRS Research Professor,"Economic History, International Economic",DR CNRS,A
29,Franz Ostrizek,Assistant Professor,"Behavioral Economics, Industrial Organisation ...",Assistant Professor,B
30,Eduardo Perez-Richet,Professor,Microeconomic Theory; Game Theory; Political E...,Full Professor,A
31,Guillaume Plantin,Professor,Monetary and Financial Economics,Full Professor,A
32,Stefan Pollinger,Assistant Professor (on secondment),"Public Economics, Applied Econometrics, and En...",Assistant Professor,B
33,Xavier Ragot,"CNRS Research Professor , OFCE Chairman","Macroeconomics, Incomplete Markets, theory and...",DR CNRS,A
34,Morgane Richard,Assistant Professor,Macroeconomics; Spatial Economics; Household F...,Assistant Professor,B
35,Jean-Marc Robin,Professor,"Labour markets, Econometrics, Microeconomics",Full Professor,A
36,Clara Santamaria,Assistant Professor,"spatial economics, macro, and labor, with a pa...",Assistant Professor,B
37,Moritz Schularick,Professor,"Macrofinance, Banking and financial stability,...",Full Professor,A
38,Jack Willis,Professor,Development Economics; Behavioural & Experimen...,Full Professor,A

# AMSE

## extraction du nom des chercheurs

In [15]:
import requests
from bs4 import BeautifulSoup

headers = {"User-Agent": "Mozilla/5.0"}

base_url = "https://www.amse-aixmarseille.fr/fr/membres?field_pr_member_type_target_id=29&field_pr_department_target_id=All&field_pr_full_name_value=&page="

names = []

for page in range(0,8):

    url = base_url + str(page)

    response = requests.get(url, headers=headers)
    response.encoding = "utf-8"

    soup = BeautifulSoup(response.text, "html.parser")

    blocks = soup.find_all("div", class_="views-field-field-pr-last-name")

    for block in blocks:

        name = block.get_text(" ", strip=True)
        names.append(name)

print(names)

['Mohammad Abu-Zaineh', 'Marcel Aloy', 'Frédéric Aprahamian', 'Dominique Augey', 'Patricia Augier', 'Guillaume Bazot', 'Mohamed Belhaj', 'Nicolas Berman', 'Pierre Bertrand', 'Sebastian Bervoets', 'Vincent Bignon', 'Raouf Boucekkine', 'Renaud Bourlès', 'Yann Bramoullé', 'Olivier Chanel', 'Nicolas Clootens', 'Jernej Copic', 'Russell Davidson', 'Marion Davin', 'Bruno Decreuse', 'Timothée Demont', 'Frédéric Deroïan', 'Habiba Djebbari', 'Marion Dovis', 'Frédéric Dufourt', 'Gilles Dufrénot', 'Alice Fabre', 'Mathieu Faure', 'Lisandro Fermin', 'Romain Ferrali', 'Nathalie Ferrière', 'Charles Figuières', 'Emmanuel Flachaire', 'Marco Fongoni', 'Gaëtan Fournier', 'Ewen Gallic', 'Cecilia Garcia Peñalosa', 'Pierre Garello', 'Karine Gente', 'Antoine Gentier', 'Badih Ghattas', 'Céline Gimet', 'Eric Girardin', 'Charles Gottlieb', 'Yajna Govind', 'Pierre Granier', 'Nicolas Gravel', 'Arthur Guillouzouic', 'Houda Hafidi', 'Julien Hanoteau', 'Dominique Henriet', 'Fanny Henriet', 'Sullivan Hué', 'Hélène Laurent', 'Sébastien Laurent', 'Didier Laussel', 'Ségal Le Guern Herry', 'Christelle Lecourt', 'Quentin Lippmann', 'Michel Lubrano', 'Stéphane Luchini', 'Hervé Magnouloux', 'Paolo Melindi-Ghidi', 'Pierre Michel', 'Eva Moreno Galbis', 'Christophe Muller', 'Alain Paraponaris', 'Patrick Pintus', 'Céline Poilly', 'Costin Protopopescu', 'Eva Raiber', 'Morgan Raux', 'Frédéric Rychen', 'Marc Sangnier', 'Christian Schluter', 'Thomas Seegmuller', 'Avner Seror', 'Antoine Soubeyran', 'Hubert Stahn', 'Miriam Teschl', 'Agnes Tomini', 'Alain Trannoy', 'Federico Trionfetti', 'Tanguy van Ypersele', 'Alain Venditti', 'Bruno Ventelou', 'Jiakun Zheng', 'Roberta Ziparo']

In [16]:
import pandas as pd

df_amse = pd.DataFrame(names, columns=["name"])

print(df_amse)

                   name
0   Mohammad Abu-Zaineh
1           Marcel Aloy
2   Frédéric Aprahamian
3       Dominique Augey
4       Patricia Augier
..                  ...
83  Tanguy van Ypersele
84       Alain Venditti
85       Bruno Ventelou
86         Jiakun Zheng
87       Roberta Ziparo

[88 rows x 1 columns]

In [17]:
import unidecode
import re

def build_amse_url(name):

    parts = name.split()

    first = parts[0]
    last_parts = parts[1:]   # tout le reste = nom de famille

    last = "-".join(last_parts)

    # enlever accents
    last = unidecode.unidecode(last.lower())

    # enlever caractères spéciaux
    last = re.sub(r"[^a-z\-]", "", last)

    url = f"https://www.amse-aixmarseille.fr/fr/membres/{last}"

    return url

## scrapping de la bio des chercheurs

In [18]:
def scrape_amse_profile(url):

    headers = {"User-Agent": "Mozilla/5.0"}

    response = requests.get(url, headers=headers)
    response.encoding = "utf-8"

    soup = BeautifulSoup(response.text, "html.parser")

    # name
    name_tag = soup.find("div", class_="field--name-field-pr-full-name")
    name = name_tag.get_text(strip=True) if name_tag else None

    # fonction locale (Chercheur / Professeur / etc.)
    role = None
    affiliation = None

    role_block = soup.find("div", class_="fs-5")

    if role_block:
        spans = role_block.find_all("span")
        if len(spans) >= 2:
            role = spans[0].get_text(strip=True)
            affiliation = spans[1].get_text(strip=True)

    # statut
    statut = None
    statut_block = soup.find("dt", string="Statut")
    if statut_block:
        statut = statut_block.find_next("dd").get_text(" ", strip=True)

    # research fields
    research = None
    research_block = soup.find("dt", string="Domaine(s) de recherche")
    if research_block:
        research = research_block.find_next("dd").get_text(" ", strip=True)

    # phd
    phd = None
    phd_block = soup.find("dt", string="Thèse")
    if phd_block:
        phd = phd_block.find_next("dd").get_text(" ", strip=True)

    # email
    email = None
    mail = soup.select_one("a[href^='mailto']")
    if mail:
        email = mail.get_text(strip=True)

    return {
        "name": name,
        "role": role,
        "affiliation": affiliation,
        "statut": statut,
        "research_fields": research,
        "phd": phd,
        "email": email
    }

In [19]:
amse_data = []

for name in df_amse["name"]:

    url = build_amse_url(name)

    profile = scrape_amse_profile(url)

    amse_data.append(profile)

df_amse_profiles = pd.DataFrame(amse_data)

In [20]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [21]:
df_amse_profiles

,name,role,affiliation,statut,research_fields,phd,email
0,Mohammad Abu-Zaineh,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Économie de la santé, Économie publique","2008, Aix-Marseille Université",mohammad.abu-zaineh[at]univ-amu.fr
1,Marcel Aloy,Chercheur,Aix-Marseille Université,Maître de conférences,"Économétrie, Macroéconomie",None,marcel.aloy[at]univ-amu.fr
2,Frédéric Aprahamian,Chercheur,Université de Toulon,Maître de conférences,"Économie comportementale et expérimentale, Économétrie, Économie de l'environnement","1991, Aix-Marseille Université",frederic.aprahamian[at]univ-amu.fr
3,Dominique Augey,Chercheuse,Aix-Marseille Université,Professeur des universités,"Philosophie économique, Économie publique","1995, Aix-Marseille Université",dominique.augey[at]univ-amu.fr
4,Patricia Augier,Chercheuse,Aix-Marseille Université,Professeur des universités,"Économie du développement, Économie internationale et géographique","1995, Aix-Marseille Université",patricia.augier[at]univ-amu.fr
5,Guillaume Bazot,Chercheur,Aix-Marseille Université,Professeur des universités,"Finance, Macroéconomie","2011, École des hautes études en sciences sociales",guillaume.bazot[at]univ-amu.fr
6,Mohamed Belhaj,Chercheur,Centrale Méditerranée,Professeur,"Finance, Théorie des jeux et réseaux sociaux","2005, University of Toulouse 1",mohamed.belhaj[at]centrale-med.fr
7,Nicolas Berman,Chercheur,CNRS,Directeur de recherche,"Économie du développement, Économie internationale et géographique","2008, Université Paris 1 Panthéon-Sorbonne",nicolas.berman[at]univ-amu.fr
8,Philippe Bertrand,Membre affilié,Aix-Marseille Université,Professeur des universités,Finance,None,philippe.bertrand[at]univ-amu.fr
9,Sebastian Bervoets,Chercheur,CNRS,Chargé de recherche,"Théorie des jeux et réseaux sociaux, Choix social","2005, Aix-Marseille Université",sebastian.bervoets[at]univ-amu.fr
10,Vincent Bignon,Chercheur,Banque de France,Professeur associé,Finance,"2002, École Polytechnique",vincent.bignon[at]banque-france.fr
11,Raouf Boucekkine,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie du développement, Macroéconomie","1993, Université Paris I Panthéon-Sorbonne",raouf.boucekkine[at]univ-amu.fr
12,Renaud Bourlès,Chercheur,Centrale Méditerranée,Professeur,"Finance, Théorie des jeux et réseaux sociaux","2008, Aix-Marseille Université",renaud.bourles[at]centrale-med.fr
13,Yann Bramoullé,Chercheur,CNRS,Directeur de recherche,"Économie de l'environnement, Théorie des jeux et réseaux sociaux","2002, University of Maryland",yann.bramoulle[at]univ-amu.fr
14,Olivier Chanel,Chercheur,CNRS,Directeur de recherche,"Économétrie, Économie de l'environnement, Économie de la santé","1993, École des hautes études en sciences sociales",olivier.chanel[at]univ-amu.fr
15,Nicolas Clootens,Chercheur,Centrale Méditerranée,Maître de conférences,"Économie de l'environnement, Macroéconomie","2017, University of Orléans",nicolas.clootens[at]centrale-med.fr
16,Jernej Copic,Chercheur,CNRS,Chargé de recherche,Finance,"2006, California Institute of Technology",jernej.copic[at]univ-amu.fr
17,Russell Davidson,Chercheur,Faculté d'économie et de gestion (FEG),Professeur,"Choix social, Économétrie","1977, University of British Columbia",russell.davidson[at]mcgill.ca
18,Marion Davin,Chercheuse,Aix-Marseille Université,Maître de conférences,"Économie de l'environnement, Macroéconomie","2014, Aix-Marseille Université",marion.davin[at]univ-amu.fr
19,Bruno Decreuse,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie du travail, Macroéconomie","2000, Aix-Marseille Université",bruno.decreuse[at]univ-amu.fr
20,Timothée Demont,Chercheur,Aix-Marseille Université,Maître de conférences,Économie du développement,"2012, University of Namur",timothee.demont[at]univ-amu.fr
21,Frédéric Deroïan,Chercheur,CNRS,Directeur de recherche,Théorie des jeux et réseaux sociaux,"2000, Aix-Marseille Université",frederic.deroian[at]univ-amu.fr
22,Habiba Djebbari,Chercheuse,Aix-Marseille Université,Professeur des universités,"Économie du développement, Économétrie","2004, University of Maryland",habiba.djebbari[at]univ-amu.fr
23,Marion Dovis,Chercheuse,Aix-Marseille Université,Professeur des universités,Économie du développement,"2007, Aix-Marseille Université",marion.dovis[at]univ-amu.fr
24,Frédéric Dufourt,Chercheur,Aix-Marseille Université,Professeur des universités,Macroéconomie,"2001, University Paris I Panthéon-Sorbonne",frederic.dufourt[at]univ-amu.fr
25,Gilles Dufrénot,Chercheur,Sciences Po Aix,Professeur des universités,"Économie du développement, Économétrie, Macroéconomie","1995, University of Paris 12",gilles.dufrenot[at]sciencespo-aix.fr
26,Alice Fabre,Chercheuse,Aix-Marseille Université,Maître de conférences,"Économie du développement, Macroéconomie",None,alice.fabre[at]univ-amu.fr
27,Mathieu Faure,Chercheur,Aix-Marseille Université,Professeur des universités,Théorie des jeux et réseaux sociaux,"2002, University of Marne-la-Vallée",mathieu.faure[at]univ-amu.fr
28,Lisandro Fermin,Chercheur,Aix-Marseille Université,Maître de conférences,Économétrie,"2008, Université Paris-Sud XI",lisandro.fermin[at]univ-amu.fr
29,Romain Ferrali,Chercheur,Aix-Marseille Université,Maître de conférences,"Économie du développement, Théorie des jeux et réseaux sociaux","2018, Princeton University",romain.ferrali[at]univ-amu.fr
30,Nathalie Ferrière,Chercheuse,Sciences Po Aix,Maître de conférences,Économie du développement,"2016, Paris School of Economics - École des hautes études en sciences sociales",nathalie.ferriere[at]sciencespo-aix.fr
31,Charles Figuières,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie de l'environnement, Théorie des jeux et réseaux sociaux, Économie publique","1999, Aix-Marseille Université",charles.figuieres[at]univ-amu.fr
32,Emmanuel Flachaire,Chercheur,Aix-Marseille Université,Professeur des universités,Économétrie,"1998, Aix-Marseille Université",emmanuel.flachaire[at]univ-amu.fr
33,Marco Fongoni,Chercheur,Aix-Marseille Université,Maître de conférences,"Économie comportementale et expérimentale, Macroéconomie","2017, University of Strathclyde",marco.fongoni[at]univ-amu.fr
34,Gaëtan Fournier,Chercheur,Aix-Marseille Université,Maître de conférences,Théorie des jeux et réseaux sociaux,"2015, Université Paris 1 Panthéon-Sorbonne",gaetan.fournier[at]univ-amu.fr
35,Ewen Gallic,Chercheur,Aix-Marseille Université,Maître de conférences,"Économétrie, Économie de l'environnement","2017, University of Rennes 1",ewen.gallic[at]univ-amu.fr
36,Cecilia Garcia Peñalosa,Chercheur,CNRS,Directeur de recherche,"Économie du développement, Économie du travail, Macroéconomie","1995, University of Oxford",cecilia.garcia-penalosa[at]univ-amu.fr
37,Pierre Garello,Chercheur,Aix-Marseille Université,Professeur des universités,"Philosophie économique, Économie publique, Choix social","1992, New York University",pierre.garello[at]univ-amu.fr
38,Karine Gente,Chercheuse,Aix-Marseille Université,Professeur des universités,Macroéconomie,"2001, Aix-Marseille Université",karine.gente[at]univ-amu.fr
39,Antoine Gentier,Chercheur,Aix-Marseille Université,Professeur des universités,"Finance, Économie publique","2001, Université Paris-Dauphine",antoine.gentier[at]univ-amu.fr
40,Badih Ghattas,Chercheur,Aix-Marseille Université,Professeur des universités,None,"2000, Université de la Méditerranée",badih.ghattas[at]univ-amu.fr
41,Céline Gimet,Chercheuse,Sciences Po Aix,Professeur des universités,"Économie du développement, Finance, Macroéconomie","2006, Aix-Marseille Université",celine.gimet[at]sciencespo-aix.fr
42,Eric Girardin,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Finance, Macroéconomie","1988, University of Rennes 1",eric.girardin[at]univ-amu.fr
43,Charles Gottlieb,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie du développement, Macroéconomie","2012, European University Institute",charles.gottlieb[at]univ-amu.fr
44,Yajna Govind,Chercheuse,Aix-Marseille Université,Chaire de professeur junior en économie,"Économie du travail, Économie publique","2021, Paris School of Economics",yajna.govind[at]univ-amu.fr
45,Pierre Granier,Chercheur,Aix-Marseille Université,Professeur des universités,Économie du travail,None,pierre.granier[at]univ-amu.fr
46,Nicolas Gravel,Chercheur,Aix-Marseille Université,Professeur des universités,"Philosophie économique, Économie publique, Choix social","1993, University of British Columbia - Canada",nicolas.gravel[at]univ-amu.fr
47,Arthur Guillouzouic,Chercheur,CNRS,Chargé de recherche,Économie publique,"2019, Sciences Po Paris",arthur.guillouzouic-le-corff[at]univ-amu.fr
48,Houda Hafidi,Chercheuse,Sciences Po Aix,Maître de conférences,Économie de l'environnement,"2022, University of Montpellier",houda.hafidi[at]sciencespo-aix.fr
49,Julien Hanoteau,Chercheur,KEDGE Business School,Professeur associé,"Économie du développement, Économie de l'environnement","2004, Institut d’Études Politiques de Paris",julien.hanoteau[at]kedgebs.com
50,Dominique Henriet,Chercheur,Centrale Méditerranée,Professeur émérite,"Économie de la santé, Économie publique, Finance","1985, University of Paris-Dauphine",dominique.henriet[at]centrale-med.fr
51,Dominique Henriet,Chercheur,Centrale Méditerranée,Professeur émérite,"Économie de la santé, Économie publique, Finance","1985, University of Paris-Dauphine",dominique.henriet[at]centrale-med.fr
52,Sullivan Hué,Chercheur,Aix-Marseille Université,Maître de conférences,"Économétrie, Finance","2020, Laboratoire d'Economie d'Orléans",sullivan.hue[at]univ-amu.fr
53,Sébastien Laurent,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Finance","2002, Maastricht University",sebastien.laurent[at]univ-amu.fr
54,Sébastien Laurent,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Finance","2002, Maastricht University",sebastien.laurent[at]univ-amu.fr
55,Didier Laussel,Chercheur,Aix-Marseille Université,Professeur émérite,"Économie industrielle, Économie internationale et géographique, Économie publique","1974, Université de Grenoble 2",didier.laussel[at]univ-amu.fr
56,Ségal Le Guern Herry,Chercheur,Aix-Marseille Université,Maître de conférences,Économie publique,"2024, Sciences Po Paris",segal.le-guern-herry[at]univ-amu.fr
57,Christelle Lecourt,Chercheuse,Aix-Marseille Université,Professeur des universités,Finance,"2000, University of Lille 1",christelle.lecourt[at]univ-amu.fr
58,Quentin Lippmann,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Économie du travail, Économie publique","2019, Paris School of Economics",quentin.lippmann[at]univ-amu.fr
59,Michel Lubrano,Chercheur,CNRS,Directeur de recherche émérite,"Économétrie, Économie publique, Choix social","1986, Toulouse",michel.lubrano[at]univ-amu.fr
60,Stéphane Luchini,Chercheur,CNRS,Chargé de recherche,"Économie comportementale et expérimentale, Économétrie, Économie de l'environnement","2000, Aix-Marseille Université",stephane.luchini[at]univ-amu.fr
61,Hervé Magnouloux,Chercheur,Aix-Marseille Université,Maître de conférences,Philosophie économique,"1993, Aix-Marseille Université",herve.magnouloux[at]univ-amu.fr
62,Paolo Melindi-Ghidi,Chercheur,Aix-Marseille Université,Maître de conférences,"Économie de l'environnement, Économie publique","2012, Université Catholique de Louvain",paolo.melindi-ghidi[at]univ-amu.fr
63,Pierre Michel,Chercheur,Aix-Marseille Université,Maître de conférences,Économétrie,"2016, Aix-Marseille Université",pierre.michel[at]univ-amu.fr
64,Eva Moreno Galbis,Chercheuse,Aix-Marseille Université,Professeur des universités,Économie du travail,"2004, Université Catholique de Louvain",eva.moreno-galbis[at]univ-amu.fr
65,Christophe Muller,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Économie du développement, Économie publique","1993, Paris School of Economics, EHESS",christophe.muller[at]univ-amu.fr
66,Alain Paraponaris,Chercheur,Aix-Marseille Université,Professeur des universités,Économie de la santé,"1998, École des hautes études en sciences sociales",alain.paraponaris[at]univ-amu.fr
67,Patrick Pintus,Chercheur,Aix-Marseille Université,Professeur des universités,Macroéconomie,"1997, École des hautes études en sciences sociales",papintus[at]gmail.com
68,Céline Poilly,Chercheuse,Aix-Marseille Université,Professeur des universités,Macroéconomie,"2008, University of Cergy-Pontoise",celine.poilly[at]univ-amu.fr
69,Costin Protopopescu,Chercheur,Aix-Marseille Université,Maître de conférences,"Économétrie, Économie de l'environnement, Finance","1997, Université Toulouse I",costin.protopopescu[at]univ-amu.fr
70,Eva Raiber,Chercheuse,Aix-Marseille Université,Professeur des universités,"Économie comportementale et expérimentale, Économie du développement","2019, Toulouse School of Economics",eva.raiber[at]univ-amu.fr
71,Morgan Raux,Chercheur,Aix-Marseille Université,Maître de conférences,"Économie du travail, Économie publique","2020, Aix-Marseille Université",morgan.raux[at]univ-amu.fr
72,Frédéric Rychen,Chercheur,Aix-Marseille Université,Maître de conférences,"Économie industrielle, Économie de l'environnement, Économie publique","1998, Aix-Marseille Université",frederic.rychen[at]univ-amu.fr
73,Marc Sangnier,Chercheur,Aix-Marseille Université,Professeur des universités,Économie publique,"2012, Paris School of Economics, EHESS",marc.sangnier[at]univ-amu.fr
74,Christian Schluter,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Économie du développement, Économie du travail","1997, London School of Economics",christian.schluter[at]univ-amu.fr
75,Thomas Seegmuller,Chercheur,CNRS,Directeur de recherche,"Économie de l'environnement, Macroéconomie","2001, Université Louis Pasteur",thomas.seegmuller[at]univ-amu.fr
76,Avner Seror,Chercheur,CNRS,Chargé de recherche,Économie du développement,"2018, Paris School of Economics - Paris 1",avner.seror[at]univ-amu.fr
77,Antoine Soubeyran,Chercheur,Aix-Marseille Université,Professeur émérite,"Économie comportementale et expérimentale, Économie industrielle","1975, Aix-Marseille Université",antoine.soubeyran[at]gmail.com
78,Hubert Stahn,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie de l'environnement, Économie publique, Théorie des jeux et réseaux sociaux","1991, Université Louis Pasteur",hubert.stahn[at]univ-amu.fr
79,Miriam Teschl,Chercheuse,EHESS,Maître de conférences,Philosophie économique,None,miriam.teschl[at]ehess.fr
80,Agnes Tomini,Chercheur,CNRS,Directeur de recherche,"Économie de l'environnement, Économie publique","2009, Aix-Marseille Université",agnes.tomini[at]univ-amu.fr
81,Alain Trannoy,Chercheur,EHESS,Directeur d’études émérite,"Philosophie économique, Économie publique, Choix social","1987, Université de Rennes",alain.trannoy[at]univ-amu.fr
82,Federico Trionfetti,Chercheur,Aix-Marseille Université,Professeur des universités,Économie internationale et géographique,"1996, The Graduate Institute of International and Development Studies",federico.trionfetti[at]univ-amu.fr
83,Tanguy van Ypersele,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie internationale et géographique, Économie publique","1996, Université Catholique de Louvain",tanguy.vy[at]univ-amu.fr
84,Alain Venditti,Chercheur,CNRS,Directeur de recherche,Macroéconomie,"1994, Aix-Marseille Université",alain.venditti[at]univ-amu.fr
85,Bruno Ventelou,Chercheur,CNRS,Directeur de recherche,"Économie de la santé, Macroéconomie","1995, Paris School of Economics, EHESS",bruno.ventelou[at]univ-amu.fr
86,Jiakun Zheng,Chercheur,Centrale Méditerranée,Maître de conférences,"Économie comportementale et expérimentale, Économie de l'environnement, Finance","2020, Toulouse School of Economics",jiakun.zheng[at]centrale-med.fr
87,Roberta Ziparo,Chercheuse,Aix-Marseille Université,Maître de conférences,"Économie de la santé, Économie du développement, Économie du travail","2013, University of Namur",roberta.ziparo[at]univ-amu.fr

In [22]:
df_amse_profiles["statut"].value_counts()

statut
Professeur des universités                 38
Maître de conférences                      24
Directeur de recherche                      9
Chargé de recherche                         5
Professeur émérite                          4
Professeur                                  3
Professeur associé                          2
Chaire de professeur junior en économie     1
Directeur de recherche émérite              1
Directeur d’études émérite                  1
Name: count, dtype: int64

## classification chercheur statut amses

In [23]:
def classify_amse(statut, affiliation):

    s = statut.lower() if statut else ""
    a = affiliation.lower() if affiliation else ""

    # rang A
    if "professeur des universités" in s:
        return "Professeur des universités", "A"

    if s == "professeur":
        return "Full Professor", "A"

    if "professeur associé" in s:
        return "Associate Professor", "A"

    if "directeur de recherche" in s:
        if "cnrs" in a:
            return "DR CNRS", "A"
        if "ehess" in a:
            return "DR EHESS", "A"
        return "DR", "A"

    # rang B
    if "maître de conférences" in s:
        if "ehess" in a:
            return "Maître de conférences EHESS", "B"
        return "Maître de conférences", "B"

    if "chargé de recherche" in s:
        if "cnrs" in a:
            return "CR CNRS", "B"
        if "ehess" in a:
            return "CR EHESS", "B"
        return "CR", "B"

    if "chaire de professeur junior" in s:
        return "Assistant Professor", "B"

    return None, None

In [24]:
df_amse_profiles[["profession", "rang"]] = df_amse_profiles.apply(
    lambda row: pd.Series(classify_amse(row["statut"], row["affiliation"])),
    axis=1
)

In [25]:
df_amse_profiles

,name,role,affiliation,statut,research_fields,phd,email,profession,rang
0,Mohammad Abu-Zaineh,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Économie de la santé, Économie publique","2008, Aix-Marseille Université",mohammad.abu-zaineh[at]univ-amu.fr,Professeur des universités,A
1,Marcel Aloy,Chercheur,Aix-Marseille Université,Maître de conférences,"Économétrie, Macroéconomie",None,marcel.aloy[at]univ-amu.fr,Maître de conférences,B
2,Frédéric Aprahamian,Chercheur,Université de Toulon,Maître de conférences,"Économie comportementale et expérimentale, Économétrie, Économie de l'environnement","1991, Aix-Marseille Université",frederic.aprahamian[at]univ-amu.fr,Maître de conférences,B
3,Dominique Augey,Chercheuse,Aix-Marseille Université,Professeur des universités,"Philosophie économique, Économie publique","1995, Aix-Marseille Université",dominique.augey[at]univ-amu.fr,Professeur des universités,A
4,Patricia Augier,Chercheuse,Aix-Marseille Université,Professeur des universités,"Économie du développement, Économie internationale et géographique","1995, Aix-Marseille Université",patricia.augier[at]univ-amu.fr,Professeur des universités,A
5,Guillaume Bazot,Chercheur,Aix-Marseille Université,Professeur des universités,"Finance, Macroéconomie","2011, École des hautes études en sciences sociales",guillaume.bazot[at]univ-amu.fr,Professeur des universités,A
6,Mohamed Belhaj,Chercheur,Centrale Méditerranée,Professeur,"Finance, Théorie des jeux et réseaux sociaux","2005, University of Toulouse 1",mohamed.belhaj[at]centrale-med.fr,Full Professor,A
7,Nicolas Berman,Chercheur,CNRS,Directeur de recherche,"Économie du développement, Économie internationale et géographique","2008, Université Paris 1 Panthéon-Sorbonne",nicolas.berman[at]univ-amu.fr,DR CNRS,A
8,Philippe Bertrand,Membre affilié,Aix-Marseille Université,Professeur des universités,Finance,None,philippe.bertrand[at]univ-amu.fr,Professeur des universités,A
9,Sebastian Bervoets,Chercheur,CNRS,Chargé de recherche,"Théorie des jeux et réseaux sociaux, Choix social","2005, Aix-Marseille Université",sebastian.bervoets[at]univ-amu.fr,CR CNRS,B
10,Vincent Bignon,Chercheur,Banque de France,Professeur associé,Finance,"2002, École Polytechnique",vincent.bignon[at]banque-france.fr,Associate Professor,A
11,Raouf Boucekkine,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie du développement, Macroéconomie","1993, Université Paris I Panthéon-Sorbonne",raouf.boucekkine[at]univ-amu.fr,Professeur des universités,A
12,Renaud Bourlès,Chercheur,Centrale Méditerranée,Professeur,"Finance, Théorie des jeux et réseaux sociaux","2008, Aix-Marseille Université",renaud.bourles[at]centrale-med.fr,Full Professor,A
13,Yann Bramoullé,Chercheur,CNRS,Directeur de recherche,"Économie de l'environnement, Théorie des jeux et réseaux sociaux","2002, University of Maryland",yann.bramoulle[at]univ-amu.fr,DR CNRS,A
14,Olivier Chanel,Chercheur,CNRS,Directeur de recherche,"Économétrie, Économie de l'environnement, Économie de la santé","1993, École des hautes études en sciences sociales",olivier.chanel[at]univ-amu.fr,DR CNRS,A
15,Nicolas Clootens,Chercheur,Centrale Méditerranée,Maître de conférences,"Économie de l'environnement, Macroéconomie","2017, University of Orléans",nicolas.clootens[at]centrale-med.fr,Maître de conférences,B
16,Jernej Copic,Chercheur,CNRS,Chargé de recherche,Finance,"2006, California Institute of Technology",jernej.copic[at]univ-amu.fr,CR CNRS,B
17,Russell Davidson,Chercheur,Faculté d'économie et de gestion (FEG),Professeur,"Choix social, Économétrie","1977, University of British Columbia",russell.davidson[at]mcgill.ca,Full Professor,A
18,Marion Davin,Chercheuse,Aix-Marseille Université,Maître de conférences,"Économie de l'environnement, Macroéconomie","2014, Aix-Marseille Université",marion.davin[at]univ-amu.fr,Maître de conférences,B
19,Bruno Decreuse,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie du travail, Macroéconomie","2000, Aix-Marseille Université",bruno.decreuse[at]univ-amu.fr,Professeur des universités,A
20,Timothée Demont,Chercheur,Aix-Marseille Université,Maître de conférences,Économie du développement,"2012, University of Namur",timothee.demont[at]univ-amu.fr,Maître de conférences,B
21,Frédéric Deroïan,Chercheur,CNRS,Directeur de recherche,Théorie des jeux et réseaux sociaux,"2000, Aix-Marseille Université",frederic.deroian[at]univ-amu.fr,DR CNRS,A
22,Habiba Djebbari,Chercheuse,Aix-Marseille Université,Professeur des universités,"Économie du développement, Économétrie","2004, University of Maryland",habiba.djebbari[at]univ-amu.fr,Professeur des universités,A
23,Marion Dovis,Chercheuse,Aix-Marseille Université,Professeur des universités,Économie du développement,"2007, Aix-Marseille Université",marion.dovis[at]univ-amu.fr,Professeur des universités,A
24,Frédéric Dufourt,Chercheur,Aix-Marseille Université,Professeur des universités,Macroéconomie,"2001, University Paris I Panthéon-Sorbonne",frederic.dufourt[at]univ-amu.fr,Professeur des universités,A
25,Gilles Dufrénot,Chercheur,Sciences Po Aix,Professeur des universités,"Économie du développement, Économétrie, Macroéconomie","1995, University of Paris 12",gilles.dufrenot[at]sciencespo-aix.fr,Professeur des universités,A
26,Alice Fabre,Chercheuse,Aix-Marseille Université,Maître de conférences,"Économie du développement, Macroéconomie",None,alice.fabre[at]univ-amu.fr,Maître de conférences,B
27,Mathieu Faure,Chercheur,Aix-Marseille Université,Professeur des universités,Théorie des jeux et réseaux sociaux,"2002, University of Marne-la-Vallée",mathieu.faure[at]univ-amu.fr,Professeur des universités,A
28,Lisandro Fermin,Chercheur,Aix-Marseille Université,Maître de conférences,Économétrie,"2008, Université Paris-Sud XI",lisandro.fermin[at]univ-amu.fr,Maître de conférences,B
29,Romain Ferrali,Chercheur,Aix-Marseille Université,Maître de conférences,"Économie du développement, Théorie des jeux et réseaux sociaux","2018, Princeton University",romain.ferrali[at]univ-amu.fr,Maître de conférences,B
30,Nathalie Ferrière,Chercheuse,Sciences Po Aix,Maître de conférences,Économie du développement,"2016, Paris School of Economics - École des hautes études en sciences sociales",nathalie.ferriere[at]sciencespo-aix.fr,Maître de conférences,B
31,Charles Figuières,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie de l'environnement, Théorie des jeux et réseaux sociaux, Économie publique","1999, Aix-Marseille Université",charles.figuieres[at]univ-amu.fr,Professeur des universités,A
32,Emmanuel Flachaire,Chercheur,Aix-Marseille Université,Professeur des universités,Économétrie,"1998, Aix-Marseille Université",emmanuel.flachaire[at]univ-amu.fr,Professeur des universités,A
33,Marco Fongoni,Chercheur,Aix-Marseille Université,Maître de conférences,"Économie comportementale et expérimentale, Macroéconomie","2017, University of Strathclyde",marco.fongoni[at]univ-amu.fr,Maître de conférences,B
34,Gaëtan Fournier,Chercheur,Aix-Marseille Université,Maître de conférences,Théorie des jeux et réseaux sociaux,"2015, Université Paris 1 Panthéon-Sorbonne",gaetan.fournier[at]univ-amu.fr,Maître de conférences,B
35,Ewen Gallic,Chercheur,Aix-Marseille Université,Maître de conférences,"Économétrie, Économie de l'environnement","2017, University of Rennes 1",ewen.gallic[at]univ-amu.fr,Maître de conférences,B
36,Cecilia Garcia Peñalosa,Chercheur,CNRS,Directeur de recherche,"Économie du développement, Économie du travail, Macroéconomie","1995, University of Oxford",cecilia.garcia-penalosa[at]univ-amu.fr,DR CNRS,A
37,Pierre Garello,Chercheur,Aix-Marseille Université,Professeur des universités,"Philosophie économique, Économie publique, Choix social","1992, New York University",pierre.garello[at]univ-amu.fr,Professeur des universités,A
38,Karine Gente,Chercheuse,Aix-Marseille Université,Professeur des universités,Macroéconomie,"2001, Aix-Marseille Université",karine.gente[at]univ-amu.fr,Professeur des universités,A
39,Antoine Gentier,Chercheur,Aix-Marseille Université,Professeur des universités,"Finance, Économie publique","2001, Université Paris-Dauphine",antoine.gentier[at]univ-amu.fr,Professeur des universités,A
40,Badih Ghattas,Chercheur,Aix-Marseille Université,Professeur des universités,None,"2000, Université de la Méditerranée",badih.ghattas[at]univ-amu.fr,Professeur des universités,A
41,Céline Gimet,Chercheuse,Sciences Po Aix,Professeur des universités,"Économie du développement, Finance, Macroéconomie","2006, Aix-Marseille Université",celine.gimet[at]sciencespo-aix.fr,Professeur des universités,A
42,Eric Girardin,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Finance, Macroéconomie","1988, University of Rennes 1",eric.girardin[at]univ-amu.fr,Professeur des universités,A
43,Charles Gottlieb,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie du développement, Macroéconomie","2012, European University Institute",charles.gottlieb[at]univ-amu.fr,Professeur des universités,A
44,Yajna Govind,Chercheuse,Aix-Marseille Université,Chaire de professeur junior en économie,"Économie du travail, Économie publique","2021, Paris School of Economics",yajna.govind[at]univ-amu.fr,Assistant Professor,B
45,Pierre Granier,Chercheur,Aix-Marseille Université,Professeur des universités,Économie du travail,None,pierre.granier[at]univ-amu.fr,Professeur des universités,A
46,Nicolas Gravel,Chercheur,Aix-Marseille Université,Professeur des universités,"Philosophie économique, Économie publique, Choix social","1993, University of British Columbia - Canada",nicolas.gravel[at]univ-amu.fr,Professeur des universités,A
47,Arthur Guillouzouic,Chercheur,CNRS,Chargé de recherche,Économie publique,"2019, Sciences Po Paris",arthur.guillouzouic-le-corff[at]univ-amu.fr,CR CNRS,B
48,Houda Hafidi,Chercheuse,Sciences Po Aix,Maître de conférences,Économie de l'environnement,"2022, University of Montpellier",houda.hafidi[at]sciencespo-aix.fr,Maître de conférences,B
49,Julien Hanoteau,Chercheur,KEDGE Business School,Professeur associé,"Économie du développement, Économie de l'environnement","2004, Institut d’Études Politiques de Paris",julien.hanoteau[at]kedgebs.com,Associate Professor,A
50,Dominique Henriet,Chercheur,Centrale Méditerranée,Professeur émérite,"Économie de la santé, Économie publique, Finance","1985, University of Paris-Dauphine",dominique.henriet[at]centrale-med.fr,None,None
51,Dominique Henriet,Chercheur,Centrale Méditerranée,Professeur émérite,"Économie de la santé, Économie publique, Finance","1985, University of Paris-Dauphine",dominique.henriet[at]centrale-med.fr,None,None
52,Sullivan Hué,Chercheur,Aix-Marseille Université,Maître de conférences,"Économétrie, Finance","2020, Laboratoire d'Economie d'Orléans",sullivan.hue[at]univ-amu.fr,Maître de conférences,B
53,Sébastien Laurent,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Finance","2002, Maastricht University",sebastien.laurent[at]univ-amu.fr,Professeur des universités,A
54,Sébastien Laurent,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Finance","2002, Maastricht University",sebastien.laurent[at]univ-amu.fr,Professeur des universités,A
55,Didier Laussel,Chercheur,Aix-Marseille Université,Professeur émérite,"Économie industrielle, Économie internationale et géographique, Économie publique","1974, Université de Grenoble 2",didier.laussel[at]univ-amu.fr,None,None
56,Ségal Le Guern Herry,Chercheur,Aix-Marseille Université,Maître de conférences,Économie publique,"2024, Sciences Po Paris",segal.le-guern-herry[at]univ-amu.fr,Maître de conférences,B
57,Christelle Lecourt,Chercheuse,Aix-Marseille Université,Professeur des universités,Finance,"2000, University of Lille 1",christelle.lecourt[at]univ-amu.fr,Professeur des universités,A
58,Quentin Lippmann,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Économie du travail, Économie publique","2019, Paris School of Economics",quentin.lippmann[at]univ-amu.fr,Professeur des universités,A
59,Michel Lubrano,Chercheur,CNRS,Directeur de recherche émérite,"Économétrie, Économie publique, Choix social","1986, Toulouse",michel.lubrano[at]univ-amu.fr,DR CNRS,A
60,Stéphane Luchini,Chercheur,CNRS,Chargé de recherche,"Économie comportementale et expérimentale, Économétrie, Économie de l'environnement","2000, Aix-Marseille Université",stephane.luchini[at]univ-amu.fr,CR CNRS,B
61,Hervé Magnouloux,Chercheur,Aix-Marseille Université,Maître de conférences,Philosophie économique,"1993, Aix-Marseille Université",herve.magnouloux[at]univ-amu.fr,Maître de conférences,B
62,Paolo Melindi-Ghidi,Chercheur,Aix-Marseille Université,Maître de conférences,"Économie de l'environnement, Économie publique","2012, Université Catholique de Louvain",paolo.melindi-ghidi[at]univ-amu.fr,Maître de conférences,B
63,Pierre Michel,Chercheur,Aix-Marseille Université,Maître de conférences,Économétrie,"2016, Aix-Marseille Université",pierre.michel[at]univ-amu.fr,Maître de conférences,B
64,Eva Moreno Galbis,Chercheuse,Aix-Marseille Université,Professeur des universités,Économie du travail,"2004, Université Catholique de Louvain",eva.moreno-galbis[at]univ-amu.fr,Professeur des universités,A
65,Christophe Muller,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Économie du développement, Économie publique","1993, Paris School of Economics, EHESS",christophe.muller[at]univ-amu.fr,Professeur des universités,A
66,Alain Paraponaris,Chercheur,Aix-Marseille Université,Professeur des universités,Économie de la santé,"1998, École des hautes études en sciences sociales",alain.paraponaris[at]univ-amu.fr,Professeur des universités,A
67,Patrick Pintus,Chercheur,Aix-Marseille Université,Professeur des universités,Macroéconomie,"1997, École des hautes études en sciences sociales",papintus[at]gmail.com,Professeur des universités,A
68,Céline Poilly,Chercheuse,Aix-Marseille Université,Professeur des universités,Macroéconomie,"2008, University of Cergy-Pontoise",celine.poilly[at]univ-amu.fr,Professeur des universités,A
69,Costin Protopopescu,Chercheur,Aix-Marseille Université,Maître de conférences,"Économétrie, Économie de l'environnement, Finance","1997, Université Toulouse I",costin.protopopescu[at]univ-amu.fr,Maître de conférences,B
70,Eva Raiber,Chercheuse,Aix-Marseille Université,Professeur des universités,"Économie comportementale et expérimentale, Économie du développement","2019, Toulouse School of Economics",eva.raiber[at]univ-amu.fr,Professeur des universités,A
71,Morgan Raux,Chercheur,Aix-Marseille Université,Maître de conférences,"Économie du travail, Économie publique","2020, Aix-Marseille Université",morgan.raux[at]univ-amu.fr,Maître de conférences,B
72,Frédéric Rychen,Chercheur,Aix-Marseille Université,Maître de conférences,"Économie industrielle, Économie de l'environnement, Économie publique","1998, Aix-Marseille Université",frederic.rychen[at]univ-amu.fr,Maître de conférences,B
73,Marc Sangnier,Chercheur,Aix-Marseille Université,Professeur des universités,Économie publique,"2012, Paris School of Economics, EHESS",marc.sangnier[at]univ-amu.fr,Professeur des universités,A
74,Christian Schluter,Chercheur,Aix-Marseille Université,Professeur des universités,"Économétrie, Économie du développement, Économie du travail","1997, London School of Economics",christian.schluter[at]univ-amu.fr,Professeur des universités,A
75,Thomas Seegmuller,Chercheur,CNRS,Directeur de recherche,"Économie de l'environnement, Macroéconomie","2001, Université Louis Pasteur",thomas.seegmuller[at]univ-amu.fr,DR CNRS,A
76,Avner Seror,Chercheur,CNRS,Chargé de recherche,Économie du développement,"2018, Paris School of Economics - Paris 1",avner.seror[at]univ-amu.fr,CR CNRS,B
77,Antoine Soubeyran,Chercheur,Aix-Marseille Université,Professeur émérite,"Économie comportementale et expérimentale, Économie industrielle","1975, Aix-Marseille Université",antoine.soubeyran[at]gmail.com,None,None
78,Hubert Stahn,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie de l'environnement, Économie publique, Théorie des jeux et réseaux sociaux","1991, Université Louis Pasteur",hubert.stahn[at]univ-amu.fr,Professeur des universités,A
79,Miriam Teschl,Chercheuse,EHESS,Maître de conférences,Philosophie économique,None,miriam.teschl[at]ehess.fr,Maître de conférences EHESS,B
80,Agnes Tomini,Chercheur,CNRS,Directeur de recherche,"Économie de l'environnement, Économie publique","2009, Aix-Marseille Université",agnes.tomini[at]univ-amu.fr,DR CNRS,A
81,Alain Trannoy,Chercheur,EHESS,Directeur d’études émérite,"Philosophie économique, Économie publique, Choix social","1987, Université de Rennes",alain.trannoy[at]univ-amu.fr,None,None
82,Federico Trionfetti,Chercheur,Aix-Marseille Université,Professeur des universités,Économie internationale et géographique,"1996, The Graduate Institute of International and Development Studies",federico.trionfetti[at]univ-amu.fr,Professeur des universités,A
83,Tanguy van Ypersele,Chercheur,Aix-Marseille Université,Professeur des universités,"Économie internationale et géographique, Économie publique","1996, Université Catholique de Louvain",tanguy.vy[at]univ-amu.fr,Professeur des universités,A
84,Alain Venditti,Chercheur,CNRS,Directeur de recherche,Macroéconomie,"1994, Aix-Marseille Université",alain.venditti[at]univ-amu.fr,DR CNRS,A
85,Bruno Ventelou,Chercheur,CNRS,Directeur de recherche,"Économie de la santé, Macroéconomie","1995, Paris School of Economics, EHESS",bruno.ventelou[at]univ-amu.fr,DR CNRS,A
86,Jiakun Zheng,Chercheur,Centrale Méditerranée,Maître de conférences,"Économie comportementale et expérimentale, Économie de l'environnement, Finance","2020, Toulouse School of Economics",jiakun.zheng[at]centrale-med.fr,Maître de conférences,B
87,Roberta Ziparo,Chercheuse,Aix-Marseille Université,Maître de conférences,"Économie de la santé, Économie du développement, Économie du travail","2013, University of Namur",roberta.ziparo[at]univ-amu.fr,Maître de conférences,B

In [26]:
df_amse_profiles["affiliation"].value_counts()

affiliation
Aix-Marseille Université                  57
CNRS                                      15
Centrale Méditerranée                      6
Sciences Po Aix                            4
EHESS                                      2
Banque de France                           1
Université de Toulon                       1
Faculté d'économie et de gestion (FEG)     1
KEDGE Business School                      1
Name: count, dtype: int64

In [27]:
df_amse_profiles = df_amse_profiles[~df_amse_profiles["statut"].str.contains("émérite", case=False, na=False)]

In [28]:
df_amse_profiles = df_amse_profiles[~df_amse_profiles["affiliation"].str.contains("KEDGE Business School", case=False, na=False)]

In [29]:
df_amse_profiles = df_amse_profiles[~df_amse_profiles["affiliation"].str.contains("Banque de France", case=False, na=False)]

In [30]:
df_amse_profiles["profession"].value_counts()

profession
Professeur des universités     38
Maître de conférences          23
DR CNRS                         9
CR CNRS                         5
Full Professor                  3
Assistant Professor             1
Maître de conférences EHESS     1
Name: count, dtype: int64

In [31]:
df_amse_profiles["profession"].unique()

array(['Professeur des universités', 'Maître de conférences',
       'Full Professor', 'DR CNRS', 'CR CNRS', 'Assistant Professor',
       'Maître de conférences EHESS'], dtype=object)

# on crée le genre à partir de la variable rôle qui donne chercheuse ou chercheur

In [32]:
df_amse_profiles["gender"] = df_amse_profiles["role"].map({
    "Chercheuse": "Female",
    "Chercheur": "Male"
})

In [33]:
df_amse_profiles["gender"].value_counts()

gender
Male      62
Female    17
Name: count, dtype: int64

In [34]:
gender_by_prof = (
    df_amse_profiles
    .groupby(["profession", "gender"])
    .size()
    .unstack(fill_value=0)
)

In [35]:
1+1

2

In [36]:
gender_by_prof["share_female"] = (
    gender_by_prof["Female"] /
    (gender_by_prof["Female"] + gender_by_prof["Male"])
)

In [37]:
gender_by_prof

gender                       Female  Male  share_female
profession
Assistant Professor               1     0      1.000000
CR CNRS                           0     5      0.000000
DR CNRS                           0     9      0.000000
Full Professor                    0     3      0.000000
Maître de conférences             5    18      0.217391
Maître de conférences EHESS       1     0      1.000000
Professeur des universités       10    27      0.270270

# TSE

## récupération du nom des chercheurs

In [38]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

headers = {"User-Agent": "Mozilla/5.0"}

data = []

for page in range(0,20):

    url = f"https://www.tse-fr.eu/fr/people/1777/-1/-1?page={page}"

    response = requests.get(url, headers=headers)
    response.encoding = "utf-8"

    soup = BeautifulSoup(response.text, "html.parser")

    rows = soup.select("div.views-row")

    if len(rows) == 0:
        break

    for row in rows:

        name = row.select_one(".cell.name")
        name = name.get_text(strip=True) if name else None

        cells = row.select(".cell")

        title = None
        role = None

        if len(cells) >= 3:
            title = cells[2].get_text(strip=True)

        if len(cells) >= 4:
            role = cells[3].get_text(strip=True)

        link = row.select_one("a.line")

        profile_url = None
        if link:
            profile_url = "https://www.tse-fr.eu" + link["href"]

        data.append({
            "name": name,
            "appelation_site": title,
            "role": role,
            "profile_url": profile_url
        })

df_tse = pd.DataFrame(data)

print(df_tse)
print("Nombre de chercheurs :", len(df_tse))

                          name  \
0         Angélique Acquatella
1                  David Alary
2                 Ingela Alger
3    Bénédicte Alziary Chassat
4                 Stefan Ambec
5          Jean-Pierre Amigues
6             Henrik Andersson
7              Tiziana Assenza
8                 Andrea Attar
9            Emmanuelle Auriol
10              Jean-Paul Azam
11             Victoria Barham
12               Pascal Bégout
13                Milo Bianchi
14          Christophe Bisière
15             Adrien Blanchet
16                Matteo Bobba
17                Jérôme Bolte
18      Jean-François Bonnefon
19               Céline Bonnet
20          Christian Bontemps
21            Philippe Bontems
22    Zohra Bouamra-Mechemache
23      Michel-Benoit Bouissou
24             Rachid Boumahdi
25            Matthieu Bouvard
26    Marie-Françoise Calmette
27            Stéphane Caprice
28         Catherine Casamatta
29           Sandrine Casanova
30          Charlotte Cavaillé
31            Catherine Cazals
32        Sylvain Chabé-Ferret
33              Daniel L. Chen
34        Frédéric Cherbonnier
35                Julien Chhor
36             Fabrice Collard
37              Claude Crampes
38              Jacques Crémer
39              Helmuth Cremer
40            Abdelaati Daouia
41       Charlotte De Cannière
42          Philippe De Donder
43           Olivier De Groote
44           Jean-Paul Décamps
45               Fany Declerck
46                Maxime Derex
47           Marion Desquilbet
48               Roberta Dessi
49       Alexandre de Cornière
50                Paul Diegert
51              Isabelle Dubec
52               Pierre Dubois
53            Martial Dupaigne
54              Isis Durrmeyer
55            Olivier Faugeras
56                Patrick Fève
57         Jean-Pierre Florens
58             Sébastien Gadat
59                 Farid Gasmi
60                Eric Gautier
61                  Victor Gay
62                 Ana Gazmuri
63           Fabien Gensbittel
64          Bertrand Gobillard
65           Christian Gollier
66                Renato Gomes
67     Eugenia Gonzalez-Aguado
68             Catarina Goulão
69               André Grimaud
70              Christine Grün
71           Alexander Guembel
72                 Ulrich Hege
73           Christian Hellwig
74               César Hidalgo
75              Marion Hoffman
76             Johannes Hörner
77                  Aude Illig
78                 Marc Ivaldi
79               Doh-Shin Jeon
80                 Chuqing Jin
81               Koen Jochmans
82               Bruno Jullien
83              Norbert Ladoux
84             Pascal Lavergne
85            Michel Le Breton
86                 Eve Leconte
87            Yassine Lefouili
88       Jean-Marie Lozachmeur
89              Thierry Magnac
90             Thomas Mariotti
91             David Martimort
92            Christine Maurel
93                Nour Meddahi
94          Kristin Michelitch
95               Laurent Miclo
96      Josepa Miquel-Florensa
97            Anouch Missirian
98      Ahmed Ezzeldin Mohamed
99               Sophie Moinas
100            Catherine Molho
101        Georges Molins-Ysal
102           Mateo Montenegro
103          Maximilian Müller
104              Céline Nauges
105           Manh-Hung Nguyen
106               Hervé Ossard
107            Edouard Pauwels
108           Isabelle Pechoux
109                 Jorge Peña
110             Olivier Perrin
111            François Poinas
112           Sébastien Pouget
113           Vincent Rebeyrol
114              Soenje Reiche
115             Jérôme Renault
116         Vincent Réquillart
117                Patrick Rey
118           Mathias Reynaert
119             Arnaud Reynaud
120              Andrew Rhodes
121        Jean-Charles Rochet
122            Silvia Rossetto
123               Anne M. Ruiz
124           François Salanié
125              Mohamed Saleh
126         Anna Sanktjohanser
127              Ian Schindler
128             Paul Seabright
129            Sara Shahanaghi
130                Alex Smolin
131         Jonathan Stieglitz
132            Stéphane Straub
133           Augustin Tapsoba
134          Emmanuel Thibault
135     Christine Thomas-Agnan
136                Jean Tirole
137             Nicolas Treich
138    Karine Van Der Straeten
139        Stéphane Villeneuve
140       Ekaterina Voltchkova
141           Vera Zaporozhets
142             Bruno Ziliotto

                                                                           appelation_site  \
0                                                              Professeure assistante, TSE
1                                          Professeur et Doyen Adjoint Pôle Formation, TSE
2                                                             Directeur de recherche, CNRS
3                                                                          Professeur, TSE
4                                                            Directeur de recherche, INRAe
5                                                            Directeur de recherche, INRAe
6                                                                  Professeur associé, TSE
7                                                     Professeure associée d'Economie, TSE
8                                                                Chargé de recherche, CNRS
9                                                               Professeur d'Economie, TSE
10                                                                 Professeur Emérite, TSE
11                                                               Directrice de l'école TSE
12                                           Maître de conférences à TSE & Manager IMT-TSE
13                                                               Professeur (TSE-TSM), TSE
14                                  Professeur de Finance (TSE-TSM), TSE. Congé sabbatique
15                                                              Maître de conférences, TSE
16                                                              Professeur d'Economie, TSE
17                                                       Professeur, TSE. Congé sabbatique
18                                                            Directeur de recherche, CNRS
19                                                          Directrice de recherche, INRAe
20                                                       Professeur d'Economie, ENAC & TSE
21                                                           Directeur de recherche, INRAe
22                                              Directrice de recherche en Economie, INRAe
23                             Maître de conférences émérite, Université Toulouse Capitole
24                                     Maître de conférences, Université Toulouse Capitole
25                                                    Professeur de Finance (TSE-TSM), TSE
26                                                                 Professeur Emérite, TSE
27                                                  Chargé de recherche en Economie, INRAe
28                                                    Professeur de Finance (TSE-TSM), TSE
29                                                           Maîtresse de conférences, TSE
30                                                   Professeure en science politique, TSE
31                                                              Maître de conférences, TSE
32                                                       Ingénieur de recherche, INRAe-TSE
33                                          Directeur de recherche, CNRS, en disponibilité
34                                    Professeur, Institut d'Etudes Politiques de Toulouse
35                                                               Professeur assistant, TSE
36                            Directeur de l'école doctorale, Directeur de recherche, CNRS
37                                                                 Professeur Emérite, TSE
38                                                              Professeur d'Economie, TSE
39                                                 Professeur de Sciences Economiques, TSE
40                                                        Professeur de Mathématiques, TSE
41                                                              Assistante professeur, TSE
42                                                            Directeur de recherche, CNRS
43                                                                         Professeur, TSE
44                                                        Professeur de Mathématiques, TSE
45                                                    Professeur de Finance (TSE-TSM), TSE
46                                                               Chargé de recherche, CNRS
47                                                 Chargée de recherche en Economie, INRAe
48                                            Maître de conférences, TSE, en disponibilité
49                                                                         Professeur, TSE
50                                                               Professeur assistant, TSE
51                                                              Maître de conférences, TSE
52                                                              Professeur d'Economie, TSE
53                                        Professeur d'Economie, Université  Montpellier 3
54                                                                        Professeure, TSE
55                                                              Maître de conférences, TSE
56                                                              Professeur d'Économie, TSE
57                                                                 Professeur Emérite, TSE
58                                                        Professeur de Mathématiques, TSE
59                                     Professeur d'Economie, Université Toulouse Capitole
60                                                                         Professeur, TSE
61                                                   Professeur assistant en Economie, TSE
62                                                             Professeure assistante, TSE
63                                                              Maître de conférences, TSE
64                                                              Maître de conférences, TSE
65                                                                   Professeur d'économie
66                                                                   En disponibilité, TSE
67                               Professeure assistante en Economie, TSE, en disponibilité
68                                  Chargé de recherches en Economie associé (INRAE & TSE)
69                                                                 Professeur Emérite, TSE
70                                                              Maître de conférences, TSE
71                                                    Professeur de Finance (TSE-TSM), TSE
72                                                              Professeur de Finance, TSE
73                                            Professeur d’Economie, TSE. Congé sabbatique
74                                                                         Professeur, TSE
75                                                               Professeur assistant, TSE
76                                                             Professeur d'Economie, CNRS
77                                                              Maître de conférences, TSE
78   Directeur d'Etudes à l'Ecole des Hautes Etudes en Sciences Sociales, Toulouse (EHESS)
79                                                              Professeur d'Economie, TSE
80                                                               Professeur assistant, TSE
81                                                              Professeur d'Economie, TSE
82                                                           Directeur de recherches, CNRS
83                                                                 Professeur Emérite, TSE
84                                                                         Professeur, TSE
85                                                      Professeur émérite d'Economie, TSE
86                                                              Maître de conférences, TSE
87                                                                   Professeur d'économie
88                                                            Directeur de recherche, CNRS
89                                  Directeur Scientifique et Doyen de la Recherche de TSE
90                                                            Directeur de recherche, CNRS
91                                                              Professeur d'Economie, TSE
92                                                              Maître de conférences, TSE
93                                                                         Professeur, TSE
94                                          Professeur associé de Sciences Politiques, TSE
95                                                            Directeur de recherche, CNRS
96                                                              Maître de conférences, TSE
97                                                             Chargée de recherche, INRAe
98                                                               Professeur assistant, TSE
99                                  Professeur de Finance (TSE-TSM), TSE. Congé sabbatique
100                                                              Professeur assistant, TSE
101                                                                Professeur Emérite, TSE
102                                                              Professeur assistant, TSE
103                                                              Professeur assistant, TSE
104                                                          Directeur de Recherche, INRAe
105                                                             Chargé de recherche, INRAe
106                                                      Conseiller de la direction de TSE
107                                                                        Professeur, TSE
108                                                             Maître de conférences, TSE
109                                                                        Professeur, TSE
110                                    Maître de conférences, Université Toulouse Capitole
111                                    Maître de conférences et Doyen de la Formation, TSE
112                Directeur de TSE-P et professeur, Université Toulouse Capitole, TSE-TSM
113                                                             Maître de conférences, TSE
114                                                  Congé sabbatique : Université de Yale
115                                            Professeur en Mathématiques Appliquées, TSE
116                                                         Professeur Emérite, INRAe -TSE
117                                                Professeur de Sciences Économiques, TSE
118                                                             Professeur d'économie, TSE
119                                                               Directeur de l'UMR TSE R
120                                                                        Professeur, TSE
121                                                             Professeur d'Economie, TSE
122                                                  Professeure de Finance (TSE-TSM), TSE
123                                             Professeur en Mathématiques Appliqués, TSE
124                                                                       Chercheur, INRAe
125                            Professeur d'Histoire Economique à la LSE, en disponibilité
126                                                            Professeure assistante, TSE
127                                                     Maître de conférences émérite, TSE
128                                                             Professeur d'Economie, TSE
129                                                            Professeure assistante, TSE
130                                                   Assistant professeur d'Economie, TSE
131                                                                        Professeur, TSE
132                                      Economiste à la Banque mondiale, en disponibilité
133                                                              Professeur assistant, TSE
134                                         Professeur d'Economie, Université de Perpignan
135                                                               Professeure émérite, TSE
136                                                         Président honoraire TSE & IAST
137                                                                       Chercheur, INRAe
138                         Directrice Générale de la Fondation Jean-Jacques Laffont - TSE
139                                                       Professeur de Mathématiques, TSE
140                                                             Maître de conférences, TSE
141                                                              Chargée de recherche, TSE
142                                                              Chargé de recherche, CNRS

                   role  \
0        Chercheuse TSE
1         Chercheur TSE
2    Chercheur IAST/TSE
3         Chercheur TSE
4         Chercheur TSE
5         Chercheur TSE
6         Chercheur TSE
7        Chercheuse TSE
8         Chercheur TSE
9         Chercheur TSE
10        Chercheur TSE
11       Chercheuse TSE
12        Chercheur TSE
13        Chercheur TSE
14        Chercheur TSE
15        Chercheur TSE
16        Chercheur TSE
17        Chercheur TSE
18   Chercheur IAST/TSE
19       Chercheuse TSE
20        Chercheur TSE
21        Chercheur TSE
22       Chercheuse TSE
23        Chercheur TSE
24        Chercheur TSE
25        Chercheur TSE
26        Chercheur TSE
27        Chercheur TSE
28        Chercheur TSE
29       Chercheuse TSE
30   Chercheur IAST/TSE
31        Chercheur TSE
32        Chercheur TSE
33   Chercheur IAST/TSE
34        Chercheur TSE
35        Chercheur TSE
36        Chercheur TSE
37        Chercheur TSE
38        Chercheur TSE
39        Chercheur TSE
40        Chercheur TSE
41        Chercheur TSE
42        Chercheur TSE
43        Chercheur TSE
44        Chercheur TSE
45        Chercheur TSE
46   Chercheur IAST/TSE
47       Chercheuse TSE
48   Chercheur IAST/TSE
49        Chercheur TSE
50        Chercheur TSE
51        Chercheur TSE
52        Chercheur TSE
53        Chercheur TSE
54       Chercheuse TSE
55        Chercheur TSE
56        Chercheur TSE
57        Chercheur TSE
58        Chercheur TSE
59        Chercheur TSE
60        Chercheur TSE
61   Chercheur IAST/TSE
62       Chercheuse TSE
63        Chercheur TSE
64        Chercheur TSE
65        Chercheur TSE
66        Chercheur TSE
67       Chercheuse TSE
68        Chercheur TSE
69        Chercheur TSE
70        Chercheur TSE
71        Chercheur TSE
72        Chercheur TSE
73        Chercheur TSE
74   Chercheur IAST/TSE
75   Chercheur IAST/TSE
76        Chercheur TSE
77        Chercheur TSE
78        Chercheur TSE
79        Chercheur TSE
80        Chercheur TSE
81        Chercheur TSE
82        Chercheur TSE
83        Chercheur TSE
84        Chercheur TSE
85        Chercheur TSE
86        Chercheur TSE
87        Chercheur TSE
88        Chercheur TSE
89        Chercheur TSE
90        Chercheur TSE
91        Chercheur TSE
92        Chercheur TSE
93        Chercheur TSE
94   Chercheur IAST/TSE
95        Chercheur TSE
96        Chercheur TSE
97       Chercheuse TSE
98   Chercheur IAST/TSE

In [148]:
df_tse["appelation_site"].value_counts()

appelation_site
Maître de conférences, TSE                                                               14
Professeur, TSE                                                                          11
Professeur d'Economie, TSE                                                                9
Professeur assistant, TSE                                                                 9
Directeur de recherche, CNRS                                                              6
Professeure assistante, TSE                                                               4
Professeur de Mathématiques, TSE                                                          4
Chargé de recherche, CNRS                                                                 3
Directeur de recherche, INRAe                                                             3
Maître de conférences, Université Toulouse Capitole                                       2
Professeur d'économie                                                                     2
Chercheur, INRAe                                                                          2
Professeur associé, TSE                                                                   1
Professeur, TSE. Congé sabbatique                                                         1
Directrice de l'école TSE                                                                 1
Maître de conférences à TSE & Manager IMT-TSE                                             1
Professeur (TSE-TSM), TSE                                                                 1
Directrice de recherche en Economie, INRAe                                                1
Professeur d'Economie, ENAC & TSE                                                         1
Directrice de recherche, INRAe                                                            1
Maîtresse de conférences, TSE                                                             1
Professeure en science politique, TSE                                                     1
Ingénieur de recherche, INRAe-TSE                                                         1
Directeur de recherche, CNRS, en disponibilité                                            1
Chargé de recherche en Economie, INRAe                                                    1
Professeur, Institut d'Etudes Politiques de Toulouse                                      1
Directeur de l'école doctorale, Directeur de recherche, CNRS                              1
Professeur de Sciences Economiques, TSE                                                   1
Assistante professeur, TSE                                                                1
Chargée de recherche en Economie, INRAe                                                   1
Maître de conférences, TSE, en disponibilité                                              1
Professeure associée d'Economie, TSE                                                      1
Professeur et Doyen Adjoint Pôle Formation, TSE                                           1
Professeure, TSE                                                                          1
Professeur d'Economie, Université  Montpellier 3                                          1
Professeur d'Economie, Université Toulouse Capitole                                       1
Professeur d'Économie, TSE                                                                1
En disponibilité, TSE                                                                     1
Professeure assistante en Economie, TSE, en disponibilité                                 1
Chargé de recherches en Economie associé (INRAE & TSE)                                    1
Professeur assistant en Economie, TSE                                                     1
Professeur d'Economie, CNRS                                                               1
Directeur d'Etudes à l'Ecole des Hautes Etudes en Sciences Sociales, Toulouse (EHESS)     1
Directeur de recherches, CNRS                                                             1
Directeur Scientifique et Doyen de la Recherche de TSE                                    1
Chargée de recherche, INRAe                                                               1
Directeur de Recherche, INRAe                                                             1
Chargé de recherche, INRAe                                                                1
Professeur d’Economie, TSE. Congé sabbatique                                              1
Conseiller de la direction de TSE                                                         1
Maître de conférences et Doyen de la Formation, TSE                                       1
Congé sabbatique : Université de Yale                                                     1
Directeur de TSE-P et professeur, Université Toulouse Capitole, TSE-TSM                   1
Professeur de Sciences Économiques, TSE                                                   1
Professeur d'économie, TSE                                                                1
Directeur de l'UMR TSE R                                                                  1
Professeur en Mathématiques Appliquées, TSE                                               1
Professeur en Mathématiques Appliqués, TSE                                                1
Professeur d'Histoire Economique à la LSE, en disponibilité                               1
Assistant professeur d'Economie, TSE                                                      1
Economiste à la Banque mondiale, en disponibilité                                         1
Professeur d'Economie, Université de Perpignan                                            1
Président honoraire TSE & IAST                                                            1
Directrice Générale de la Fondation Jean-Jacques Laffont - TSE                            1
Chargée de recherche, TSE                                                                 1
Name: count, dtype: int64

# nettoyage des données en enlevant émerité, Finance, et sciences politiques

In [40]:
df_tse = df_tse[~df_tse["appelation_site"].str.contains("émérite", case=False, na=False)]

In [41]:
df_tse = df_tse[~df_tse["appelation_site"].str.contains("Emérite", case=False, na=False)]

In [42]:
df_tse = df_tse[~df_tse["appelation_site"].str.contains("Finance", case=False, na=False)]

In [43]:
df_tse = df_tse[~df_tse["appelation_site"].str.contains("science politiques", case=False, na=False)]

In [147]:
df_tse = df_tse[~df_tse["appelation_site"].str.contains("sciences politiques", case=False, na=False)]

In [139]:
def classify_tse(title):

    t = title.lower() if title else ""

    # DR
    if ("directeur de recherche" in t or 
        "directrice de recherche" in t or
        "directeur de recherches" in t or
        "directrice de recherches" in t) and "cnrs" in t:
        return "DR CNRS", "A"

    if ("directeur de recherche" in t or 
        "directrice de recherche" in t) and "inrae" in t:
        return "DR INRAE", "A"

    # CR
    if ("chargé de recherche" in t or 
        "chargée de recherche" in t or
        "chargé de recherches" in t or
        "chargée de recherches" in t) and "cnrs" in t:
        return "CR CNRS", "B"

    if ("chargé de recherche" in t or 
        "chargée de recherche" in t) and "inrae" in t:
        return "CR INRAE", "B"

    # Assistant Professor
    if ("assistant professeur" in t or
        "assistante professeur" in t or
        "professeur assistant" in t or
        "professeure assistante" in t):
        return "Assistant Professor", "B"

    # Maître de conférences
    if ("maître de conférences" in t or 
        "maîtresse de conférences" in t):
        return "Maître de conférences", "B"

    return None, None

In [140]:
df_tse[["profession","rang"]] = df_tse["appelation_site"].apply(
    lambda x: pd.Series(classify_tse(x))
)

In [141]:
len(df_tse[df_tse["profession"].notna()])

60

### on s'occupe de ceux qui n'ont pas encore été classifiés

In [47]:
import requests
from bs4 import BeautifulSoup

headers = {"User-Agent": "Mozilla/5.0"}

def get_cv_link(url):

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    cv_tag = soup.find("a", class_="lien pdf")

    if cv_tag:
        return cv_tag["href"]

    return None

In [48]:
def download_cv(cv_url, name):

    r = requests.get(cv_url, headers=headers)

    with open(f"cv/{name}.pdf", "wb") as f:
        f.write(r.content)

## récupération des cv en pdf

In [49]:
import os

os.makedirs("cv", exist_ok=True)

In [50]:
for i, row in df_tse[df_tse["profession"].isna()].iterrows():

    url = row["profile_url"]

    cv_url = get_cv_link(url)

    if cv_url:
        download_cv(cv_url, row["name"])

### analyse des cvs

In [51]:
pip install pdfplumber

Requirement already satisfied: pdfplumber in /opt/python/lib/python3.13/site-packages (0.11.9)
Requirement already satisfied: pdfminer.six==20251230 in /opt/python/lib/python3.13/site-packages (from pdfplumber) (20251230)
Requirement already satisfied: Pillow>=9.1 in /opt/python/lib/python3.13/site-packages (from pdfplumber) (12.1.1)
Requirement already satisfied: pypdfium2>=4.18.0 in /opt/python/lib/python3.13/site-packages (from pdfplumber) (5.6.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /opt/python/lib/python3.13/site-packages (from pdfminer.six==20251230->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in /opt/python/lib/python3.13/site-packages (from pdfminer.six==20251230->pdfplumber) (46.0.5)
Requirement already satisfied: cffi>=2.0.0 in /opt/python/lib/python3.13/site-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /opt/python/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)
Note: you may need to restart the kernel to use updated packages.

In [78]:
import pdfplumber

In [79]:
def extract_text_from_pdf(path):

    text = ""

    try:
        with pdfplumber.open(path) as pdf:

            for page in pdf.pages:

                page_text = page.extract_text()

                if page_text:
                    text += page_text + "\n"

    except:
        return None

    return text

In [80]:
def clean_text(text):

    text = text.lower()

    text = text.replace("assistantprofessor", "assistant professor")
    text = text.replace("associateprofessor", "associate professor")
    text = text.replace("fullprofessor", "full professor")

    text = text.replace("toulouseschoolofeconomics", "toulouse school of economics")

    return text

In [81]:
import re

def extract_current_position(text):

    lines = text.lower().split("\n")

    keywords = [
        "assistant professor",
        "directeur d'études", 
        "directeur d'etudes", 
        "associate professor",
        "chargée de recherche",
        "directrice de recherche",
        "professeure",
        "professor",
        "professeur",
        "research director",
        "directeur de recherche",
        "chargé de recherche",
        "maître de conférences",
        "researcher"
    ]

    # on regarde seulement le début du CV
    for line in lines[:20]:

        if "@" in line:
            continue

        if any(k in line for k in keywords):
            return line.strip()

    return None

In [82]:
def extract_year(line):

    match = re.search(r"(19|20)\d{2}", line)

    if match:
        return match.group()

    return None

In [83]:
def extract_past_positions(text):

    lines = text.lower().split("\n")

    positions = []

    keywords = [
        "assistant professor",
        "associate professor",
        "professor",
        "directeur d'études", 
        "directeur d'etudes",
        "maître de conférences",
        "chargé de recherche",
        "directeur de recherche",
        "director of research",
        "professeur",
        "research director",
        "researcher",
        "postdoc"
    ]

    for line in lines:

        if len(line) < 15:
            continue

        if not re.search(r"(19|20)\d{2}", line):
            continue

        if any(k in line for k in keywords):

            year_match = re.search(r"(19|20)\d{2}", line)
            year = int(year_match.group())

            positions.append({
                "year": year,
                "text": line.strip()
            })

    return positions

In [84]:
def infer_rank_from_past_positions(text):

    text = text.lower()

    if "associate professor" in text:
        return "A"

    if "full professor" in text:
        return "A"

    if "assistant professor" in text:
        return "B"

    return None

In [85]:
def detect_prof_qualification(text):

    text = text.lower()

    if "qualification aux fonctions de professeur" in text:
        return "A"
    return None

In [87]:
def extract_birth_year(text):

    match = re.search(r"(born|birth).*?(19|20)\d{2}", text.lower())

    if match:
        return match.group()

    return None

In [88]:
def extract_phd_year(text):

    text = text.lower()

    match = re.search(r'phd[^0-9]{0,20}(19|20)\d{2}', text)

    if match:
        year = re.search(r'(19|20)\d{2}', match.group())
        return int(year.group())

    return None

In [89]:
def classify_rank(position):

    if position is None:
        return None

    if position in [
        "Full Professor",
        "Professeur des universités",
        "Associate Professor",
        "Maître de conférences",
        "DR CNRS / INRAE"
    ]:
        return "A"

    if position in [
        "Assistant Professor",
        "CR CNRS / INRAE"
    ]:
        return "B"

    return None

In [90]:
def correct_rank(current_position, past_positions):

    text = ""

    if current_position:
        text += current_position.lower()

    if past_positions:
        text += " ".join([p["text"] for p in past_positions]).lower()

    # rang A
    if (
        "research director" in text
        or "directeur de recherche" in text
        or "professor" in text
        or "professeur" in text
        or "associate professor" in text
        or "maître de conférences" in text
    ):
        return "A"

    # rang B
    if (
        "assistant professor" in text
        or "chargé de recherche" in text
    ):
        return "B"

    return None

In [91]:
def extract_position(text):

    if text is None:
        return None

    text = text.lower()

    if "directeur de recherche" in text or "directrice de recherche" in text or "research director" in text or "director of research" in text:
        return "DR CNRS / INRAE"
    
    if "directeur d’études" in text or "directeur d'etudes" in text:
        return "Directeur d'études (EHESS)"

    if "chargé de recherche" in text:
        return "CR CNRS / INRAE"
    if "chargée de recherche" in text:
        return "CR CNRS / INRAE"

    if "senior researcher" in text:
         return "DR CNRS / INRAE"

    if "junior researcher" in text:
        return "CR CNRS / INRAE"

    if "assistant professor" in text:
        return "Assistant Professor"

    if "associate professor" in text:
        return "Associate Professor"

    if "maître de conférences" in text:
        return "Maître de conférences"

    if "professeur" in text or "professeure" in text:
        return "Professeur des universités"

    if "professor" in text:
        return "Full Professor"

    return None

In [92]:
def get_latest_position(past_positions):

    if not past_positions:
        return None

    valid = []

    for p in past_positions:

        if p["year"] is None:
            continue

        text = p["text"].lower()

        # ignorer postdocs / visiting
        if "post doc" in text or "postdoc" in text or "visiting" in text:
            continue

        valid.append(p)

    if not valid:
        return None

    latest = max(valid, key=lambda x: x["year"])

    return extract_position(latest["text"])

In [93]:
def analyse_cv(path):

    text = extract_text_from_pdf(path)
    if text is None:
        return None
    
    text = clean_text(text)

    current_position_site = extract_current_position(text)

    birth_year = extract_birth_year(text)

    phd_year = extract_phd_year(text)

    past_positions = extract_past_positions(text)

    # récupérer la dernière position académique
    latest_position = get_latest_position(past_positions)

    # extraction position depuis current_position
    position = extract_position(current_position_site)

    # si la position n'est pas trouvée dans current_position
    if position is None:
        position = latest_position

    # PRIORITÉ aux statuts CNRS / INRAE
    if latest_position == "DR CNRS / INRAE":
        position = "DR CNRS / INRAE"

    if latest_position == "CR CNRS / INRAE" and position not in ["DR CNRS / INRAE"]:
        position = "CR CNRS / INRAE"

    # maintenant on peut calculer le rang
    rank = classify_rank(position)

    if rank is None:
        rank = correct_rank(current_position_site, past_positions)

    return {
        "current_position": current_position_site,
        "position": position,
        "latest_position": latest_position,
        "birth_year": birth_year,
        "phd_year": phd_year,
        "rank": rank,
        "past_positions": past_positions
    }

In [96]:
results = []

for file in os.listdir("cv"):
    path = f"cv/{file}"
    print("Processing:", file)

    info = analyse_cv(path)

    if info is None:
        print("Skipping:", file)
        continue

    info["file"] = file
    results.append(info)

Processing: Hervé Ossard.pdf
Processing: César Hidalgo.pdf

Processing: Céline Bonnet.pdf
Processing: Ahmed Ezzeldin Mohamed.pdf
Processing: Milo Bianchi.pdf
Processing: Jérôme Renault.pdf
Processing: Alex Smolin.pdf
Processing: Emmanuel Thibault.pdf
Processing: Anouch Missirian.pdf
Processing: Mohamed Saleh.pdf
Processing: Pascal Lavergne.pdf
Processing: Jonathan Stieglitz.pdf
Processing: Bénédicte Alziary Chassat.pdf
Processing: Yassine Lefouili.pdf
Processing: Patrick Fève.pdf
Processing: Nour Meddahi.pdf
Processing: Christian Gollier.pdf
Processing: François Salanié.pdf
Processing: Thierry Magnac.pdf
Processing: Marc Ivaldi.pdf
Processing: Isis Durrmeyer.pdf
Processing: Nicolas Treich.pdf
Processing: David Alary.pdf
Processing: Abdelaati Daouia.pdf
Processing: Patrick Rey.pdf
Processing: Marion Hoffman.pdf
Processing: Christian Hellwig.pdf
Processing: Arnaud Reynaud.pdf
Processing: Jean-Paul Décamps.pdf
Processing: Andrew Rhodes.pdf
Processing: Julien Chhor.pdf
Processing: Jérôme Bolte.pdf
Processing: Augustin Tapsoba.pdf
Processing: Koen Jochmans.pdf
Processing: Jean-Charles Rochet.pdf
Processing: Doh-Shin Jeon.pdf
Processing: Stéphane Straub.pdf
Processing: Renato Gomes.pdf
Processing: Helmuth Cremer.pdf
Processing: Soenje Reiche.pdf
Skipping: Soenje Reiche.pdf
Processing: Henrik Andersson.pdf
Processing: Stéphane Villeneuve.pdf
Processing: Anne M. Ruiz.pdf
Processing: Farid Gasmi.pdf
Processing: Emmanuelle Auriol.pdf
Processing: Alexandre de Cornière.pdf
Processing: Eric Gautier.pdf
Processing: Johannes Hörner.pdf
Processing: Vera Zaporozhets.pdf
Processing: Eugenia Gonzalez-Aguado.pdf
Processing: Tiziana Assenza.pdf
Processing: Zohra Bouamra-Mechemache.pdf
Processing: Karine Van Der Straeten.pdf
Processing: Sébastien Pouget.pdf
Processing: Jacques Crémer.pdf
Processing: Pierre Dubois.pdf
Processing: Catherine Molho.pdf
Processing: Sébastien Gadat.pdf
Processing: Christian Bontemps.pdf
Processing: Martial Dupaigne.pdf
Processing: Mathias Reynaert.pdf
Processing: Marion Desquilbet.pdf
Processing: Jean Tirole.pdf
Processing: Sandrine Casanova.pdf
Processing: Paul Seabright.pdf
Processing: Frédéric Cherbonnier.pdf
Processing: David Martimort.pdf
Processing: Sylvain Chabé-Ferret.pdf

In [97]:
df_cv = pd.DataFrame(results)

In [98]:
df_cv["name"] = df_cv["file"].str.replace(".pdf", "", regex=False)

In [99]:
cols = ["name"] + [c for c in df_cv.columns if c != "name"]
df_cv = df_cv[cols]

In [142]:
df_cv[df_cv["position"].isna()][
    ["name","current_position","latest_position","past_positions", "rank"]
]

Empty DataFrame
Columns: [name, current_position, latest_position, past_positions, rank]
Index: []

In [111]:
df_cv["position"].value_counts()

position
Full Professor                37
DR CNRS / INRAE               10
Assistant Professor            7
Professeur des universités     7
Pas clair / à déterminer       3
Associate Professor            2
CR CNRS / INRAE                1
Name: count, dtype: int64

In [113]:
df_tse

,name,appelation_site,role,profile_url,profession,rang
0,Angélique Acquatella,"Professeure assistante, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/angelique-acquatella,None,None
1,David Alary,"Professeur et Doyen Adjoint Pôle Formation, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/david-alary,None,None
2,Ingela Alger,"Directeur de recherche, CNRS",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/ingela-alger,DR CNRS,A
3,Bénédicte Alziary Chassat,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/benedicte-alziary-chassat,None,None
4,Stefan Ambec,"Directeur de recherche, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/stefan-ambec,DR INRAE,A
5,Jean-Pierre Amigues,"Directeur de recherche, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/jean-pierre-amigues,DR INRAE,A
6,Henrik Andersson,"Professeur associé, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/henrik-andersson,None,None
7,Tiziana Assenza,"Professeure associée d'Economie, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/tiziana-assenza,None,None
8,Andrea Attar,"Chargé de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/andrea-attar,CR CNRS,B
9,Emmanuelle Auriol,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/emmanuelle-auriol,None,None
11,Victoria Barham,Directrice de l'école TSE,Chercheuse TSE,https://www.tse-fr.eu/fr/people/victoria-barham,None,None
12,Pascal Bégout,Maître de conférences à TSE & Manager IMT-TSE,Chercheur TSE,https://www.tse-fr.eu/fr/people/pascal-begout,Maître de conférences,B
13,Milo Bianchi,"Professeur (TSE-TSM), TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/milo-bianchi,None,None
15,Adrien Blanchet,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/adrien-blanchet,Maître de conférences,B
16,Matteo Bobba,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/matteo-bobba,None,None
17,Jérôme Bolte,"Professeur, TSE. Congé sabbatique",Chercheur TSE,https://www.tse-fr.eu/fr/people/jerome-bolte,None,None
18,Jean-François Bonnefon,"Directeur de recherche, CNRS",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/jean-francois-bonnefon,DR CNRS,A
19,Céline Bonnet,"Directrice de recherche, INRAe",Chercheuse TSE,https://www.tse-fr.eu/fr/people/celine-bonnet,None,None
20,Christian Bontemps,"Professeur d'Economie, ENAC & TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/christian-bontemps,None,None
21,Philippe Bontems,"Directeur de recherche, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/philippe-bontems,DR INRAE,A
22,Zohra Bouamra-Mechemache,"Directrice de recherche en Economie, INRAe",Chercheuse TSE,https://www.tse-fr.eu/fr/people/zohra-bouamra-mechemache,None,None
24,Rachid Boumahdi,"Maître de conférences, Université Toulouse Capitole",Chercheur TSE,https://www.tse-fr.eu/fr/people/rachid-boumahdi,Maître de conférences,B
27,Stéphane Caprice,"Chargé de recherche en Economie, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/stephane-caprice,CR INRAE,B
29,Sandrine Casanova,"Maîtresse de conférences, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/sandrine-casanova,None,None
30,Charlotte Cavaillé,"Professeure en science politique, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/charlotte-cavaille,None,None
31,Catherine Cazals,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/catherine-cazals,Maître de conférences,B
32,Sylvain Chabé-Ferret,"Ingénieur de recherche, INRAe-TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/sylvain-chabe-ferret,None,None
33,Daniel L. Chen,"Directeur de recherche, CNRS, en disponibilité",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/daniel-l-chen,DR CNRS,A
34,Frédéric Cherbonnier,"Professeur, Institut d'Etudes Politiques de Toulouse",Chercheur TSE,https://www.tse-fr.eu/fr/people/frederic-cherbonnier,None,None
35,Julien Chhor,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/julien-chhor,None,None
36,Fabrice Collard,"Directeur de l'école doctorale, Directeur de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/fabrice-collard,DR CNRS,A
38,Jacques Crémer,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/jacques-cremer,None,None
39,Helmuth Cremer,"Professeur de Sciences Economiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/helmuth-cremer,None,None
40,Abdelaati Daouia,"Professeur de Mathématiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/abdelaati-daouia,None,None
41,Charlotte De Cannière,"Assistante professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/charlotte-de-canniere,None,None
42,Philippe De Donder,"Directeur de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/philippe-de-donder,DR CNRS,A
43,Olivier De Groote,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/olivier-de-groote,None,None
44,Jean-Paul Décamps,"Professeur de Mathématiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/jean-paul-decamps,None,None
46,Maxime Derex,"Chargé de recherche, CNRS",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/maxime-derex,CR CNRS,B
47,Marion Desquilbet,"Chargée de recherche en Economie, INRAe",Chercheuse TSE,https://www.tse-fr.eu/fr/people/marion-desquilbet,None,None
48,Roberta Dessi,"Maître de conférences, TSE, en disponibilité",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/roberta-dessi,Maître de conférences,B
49,Alexandre de Cornière,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/alexandre-de-corniere,None,None
50,Paul Diegert,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/paul-diegert,None,None
51,Isabelle Dubec,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/isabelle-dubec,Maître de conférences,B
52,Pierre Dubois,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/pierre-dubois,None,None
53,Martial Dupaigne,"Professeur d'Economie, Université Montpellier 3",Chercheur TSE,https://www.tse-fr.eu/fr/people/martial-dupaigne,None,None
54,Isis Durrmeyer,"Professeure, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/isis-durrmeyer,None,None
55,Olivier Faugeras,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/olivier-faugeras,Maître de conférences,B
56,Patrick Fève,"Professeur d'Économie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/patrick-feve,None,None
58,Sébastien Gadat,"Professeur de Mathématiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/sebastien-gadat,None,None
59,Farid Gasmi,"Professeur d'Economie, Université Toulouse Capitole",Chercheur TSE,https://www.tse-fr.eu/fr/people/farid-gasmi,None,None
60,Eric Gautier,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/eric-gautier,None,None
61,Victor Gay,"Professeur assistant en Economie, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/victor-gay,None,None
62,Ana Gazmuri,"Professeure assistante, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/ana-gazmuri,None,None
63,Fabien Gensbittel,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/fabien-gensbittel,Maître de conférences,B
64,Bertrand Gobillard,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/bertrand-gobillard,Maître de conférences,B
65,Christian Gollier,Professeur d'économie,Chercheur TSE,https://www.tse-fr.eu/fr/people/christian-gollier,None,None
66,Renato Gomes,"En disponibilité, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/renato-gomes,None,None
67,Eugenia Gonzalez-Aguado,"Professeure assistante en Economie, TSE, en disponibilité",Chercheuse TSE,https://www.tse-fr.eu/fr/people/eugenia-gonzalez-aguado,None,None
68,Catarina Goulão,Chargé de recherches en Economie associé (INRAE & TSE),Chercheur TSE,https://www.tse-fr.eu/fr/people/catarina-goulao,CR INRAE,B
70,Christine Grün,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/christine-grun,Maître de conférences,B
73,Christian Hellwig,"Professeur d’Economie, TSE. Congé sabbatique",Chercheur TSE,https://www.tse-fr.eu/fr/people/christian-hellwig,None,None
74,César Hidalgo,"Professeur, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/cesar-hidalgo,None,None
75,Marion Hoffman,"Professeur assistant, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/marion-hoffman,None,None
76,Johannes Hörner,"Professeur d'Economie, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/johannes-horner,None,None
77,Aude Illig,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/aude-illig,Maître de conférences,B
78,Marc Ivaldi,"Directeur d'Etudes à l'Ecole des Hautes Etudes en Sciences Sociales, Toulouse (EHESS)",Chercheur TSE,https://www.tse-fr.eu/fr/people/marc-ivaldi,None,None
79,Doh-Shin Jeon,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/doh-shin-jeon,None,None
80,Chuqing Jin,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/chuqing-jin,None,None
81,Koen Jochmans,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/koen-jochmans,None,None
82,Bruno Jullien,"Directeur de recherches, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/bruno-jullien,DR CNRS,A
84,Pascal Lavergne,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/pascal-lavergne,None,None
86,Eve Leconte,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/eve-leconte,Maître de conférences,B
87,Yassine Lefouili,Professeur d'économie,Chercheur TSE,https://www.tse-fr.eu/fr/people/yassine-lefouili,None,None
88,Jean-Marie Lozachmeur,"Directeur de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/jean-marie-lozachmeur,DR CNRS,A
89,Thierry Magnac,Directeur Scientifique et Doyen de la Recherche de TSE,Chercheur TSE,https://www.tse-fr.eu/fr/people/thierry-magnac,None,None
90,Thomas Mariotti,"Directeur de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/thomas-mariotti,DR CNRS,A
91,David Martimort,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/david-martimort,None,None
92,Christine Maurel,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/christine-maurel,Maître de conférences,B
93,Nour Meddahi,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/nour-meddahi,None,None
94,Kristin Michelitch,"Professeur associé de Sciences Politiques, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/kristin-michelitch,None,None
95,Laurent Miclo,"Directeur de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/laurent-miclo,DR CNRS,A
96,Josepa Miquel-Florensa,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/josepa-miquel-florensa,Maître de conférences,B
97,Anouch Missirian,"Chargée de recherche, INRAe",Chercheuse TSE,https://www.tse-fr.eu/fr/people/anouch-missirian,None,None
98,Ahmed Ezzeldin Mohamed,"Professeur assistant, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/ahmed-ezzeldin-mohamed,None,None
100,Catherine Molho,"Professeur assistant, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/catherine-molho,None,None
102,Mateo Montenegro,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/mateo-montenegro,None,None
103,Maximilian Müller,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/maximilian-muller,None,None
104,Céline Nauges,"Directeur de Recherche, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/celine-nauges,DR INRAE,A
105,Manh-Hung Nguyen,"Chargé de recherche, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/manh-hung-nguyen,CR INRAE,B
106,Hervé Ossard,Conseiller de la direction de TSE,Chercheur TSE,https://www.tse-fr.eu/fr/people/herve-ossard,None,None
107,Edouard Pauwels,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/edouard-pauwels,None,None
108,Isabelle Pechoux,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/isabelle-pechoux,Maître de conférences,B
109,Jorge Peña,"Professeur, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/jorge-pena,None,None
110,Olivier Perrin,"Maître de conférences, Université Toulouse Capitole",Chercheur TSE,https://www.tse-fr.eu/fr/people/olivier-perrin,Maître de conférences,B
111,François Poinas,"Maître de conférences et Doyen de la Formation, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/francois-poinas,Maître de conférences,B
112,Sébastien Pouget,"Directeur de TSE-P et professeur, Université Toulouse Capitole, TSE-TSM",Chercheur TSE,https://www.tse-fr.eu/fr/people/sebastien-pouget,None,None
113,Vincent Rebeyrol,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/vincent-rebeyrol,Maître de conférences,B
114,Soenje Reiche,Congé sabbatique : Université de Yale,Chercheur TSE,https://www.tse-fr.eu/fr/people/soenje-reiche,None,None
115,Jérôme Renault,"Professeur en Mathématiques Appliquées, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/jerome-renault,None,None
117,Patrick Rey,"Professeur de Sciences Économiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/patrick-rey,None,None
118,Mathias Reynaert,"Professeur d'économie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/mathias-reynaert,None,None
119,Arnaud Reynaud,Directeur de l'UMR TSE R,Chercheur TSE,https://www.tse-fr.eu/fr/people/arnaud-reynaud,None,None
120,Andrew Rhodes,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/andrew-rhodes,None,None
121,Jean-Charles Rochet,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/jean-charles-rochet,None,None
123,Anne M. Ruiz,"Professeur en Mathématiques Appliqués, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/anne-m-ruiz,None,None
124,François Salanié,"Chercheur, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/francois-salanie,None,None
125,Mohamed Saleh,"Professeur d'Histoire Economique à la LSE, en disponibilité",Chercheur TSE,https://www.tse-fr.eu/fr/people/mohamed-saleh,None,None
126,Anna Sanktjohanser,"Professeure assistante, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/anna-sanktjohanser,None,None
128,Paul Seabright,"Professeur d'Economie, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/paul-seabright,None,None
129,Sara Shahanaghi,"Professeure assistante, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/sara-shahanaghi,None,None
130,Alex Smolin,"Assistant professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/alex-smolin,None,None
131,Jonathan Stieglitz,"Professeur, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/jonathan-stieglitz,None,None
132,Stéphane Straub,"Economiste à la Banque mondiale, en disponibilité",Chercheur TSE,https://www.tse-fr.eu/fr/people/stephane-straub,None,None
133,Augustin Tapsoba,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/augustin-tapsoba,None,None
134,Emmanuel Thibault,"Professeur d'Economie, Université de Perpignan",Chercheur TSE,https://www.tse-fr.eu/fr/people/emmanuel-thibault,None,None
136,Jean Tirole,Président honoraire TSE & IAST,Chercheur TSE,https://www.tse-fr.eu/fr/people/jean-tirole,None,None
137,Nicolas Treich,"Chercheur, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/nicolas-treich,None,None
138,Karine Van Der Straeten,Directrice Générale de la Fondation Jean-Jacques Laffont - TSE,Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/karine-van-der-straeten,None,None
139,Stéphane Villeneuve,"Professeur de Mathématiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/stephane-villeneuve,None,None
140,Ekaterina Voltchkova,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/ekaterina-voltchkova,Maître de conférences,B
141,Vera Zaporozhets,"Chargée de recherche, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/vera-zaporozhets,None,None
142,Bruno Ziliotto,"Chargé de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/bruno-ziliotto,CR CNRS,B

In [112]:
df_cv[df_cv["position"]=="Assistant Professor"]

,name,current_position,position,latest_position,birth_year,phd_year,rank,past_positions,file
3,Ahmed Ezzeldin Mohamed,"assistant professor of political science, aug. 2023-current",Assistant Professor,Assistant Professor,None,NaN,B,"[{'year': 2023, 'text': 'assistant professor of political science, aug. 2023-current'}, {'year': 2018, 'text': 'lead researcher, life makers foundation, alexandria, may 2018 – sept. 2019'}, {'year': 2013, 'text': 'researcher, tusiad competitiveness forum, istanbul, sept. 2013 – sept. 2014'}]",Ahmed Ezzeldin Mohamed.pdf
6,Alex Smolin,"2019 – present, assistant professor, toulouse school of economics",Assistant Professor,Assistant Professor,birth: 09/09/1988,2016.0,B,"[{'year': 2019, 'text': '2019 – present, assistant professor, toulouse school of economics'}]",Alex Smolin.pdf
8,Anouch Missirian,"from2021: toulouse school of economics,france. assistant professorofeconomics.",Assistant Professor,Assistant Professor,None,2016.0,B,"[{'year': 2021, 'text': 'from2021: toulouse school of economics,france. assistant professorofeconomics.'}, {'year': 2020, 'text': '2020–2021: ucsantabarbara,usa.postdoctoralscholaratemlab(environmentalmarketsolutionslab).'}]",Anouch Missirian.pdf
30,Julien Chhor,"assistant professor. toulouse, france",Assistant Professor,None,None,NaN,B,[],Julien Chhor.pdf
32,Augustin Tapsoba,"2019- assistant professor of economics, toulouse school of economics (tse)",Assistant Professor,None,born in 2021,NaN,B,"[{'year': 2019, 'text': '2019- assistant professor of economics, toulouse school of economics (tse)'}, {'year': 2024, 'text': '2024- invited researcher, the abdul latif jameel poverty action lab (j-pal), mit'}, {'year': 2024, 'text': '2024: anr team research grant (e500 000, researcher in the project of pi nour meddahi)'}]",Augustin Tapsoba.pdf
48,Eugenia Gonzalez-Aguado,"toulouse school of economics, assistant professor 2020–current",Assistant Professor,Assistant Professor,None,NaN,B,"[{'year': 2020, 'text': 'toulouse school of economics, assistant professor 2020–current'}]",Eugenia Gonzalez-Aguado.pdf
55,Catherine Molho,"assistant professor,toulouse school of economics",Assistant Professor,Assistant Professor,None,2019.0,B,"[{'year': 2024, 'text': '2024‑ assistant professor,departmentofsocialandbehavioralsciences,toulouse school of economics'}, {'year': 2022, 'text': '2022‑2024 assistant professor,departmentofexperimentalandappliedpsychology,vuamsterdam'}, {'year': 2017, 'text': '•committeememberforbestdissertationaward,dutchassociationofsocialpsychologyresearchers(aspo)(2017‑2018)'}]",Catherine Molho.pdf

In [117]:
df_cv.columns

Index(['name', 'current_position', 'position', 'latest_position', 'birth_year',
       'phd_year', 'rank', 'past_positions', 'file'],
      dtype='object')

In [149]:
df_merge = df_tse.merge(
    df_cv[["name","position","rank"]],
    on="name",
    how="left"
)

In [150]:
df_merge["profession"] = df_merge["profession"].fillna(df_merge["position"])
df_merge["rang"] = df_merge["rang"].fillna(df_merge["rank"])

In [151]:
df_merge = df_merge.drop(columns=["position","rank"])

In [152]:
df_merge

,name,appelation_site,role,profile_url,profession,rang
0,Angélique Acquatella,"Professeure assistante, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/angelique-acquatella,Assistant Professor,B
1,David Alary,"Professeur et Doyen Adjoint Pôle Formation, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/david-alary,Associate Professor,A
2,Ingela Alger,"Directeur de recherche, CNRS",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/ingela-alger,DR CNRS,A
3,Bénédicte Alziary Chassat,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/benedicte-alziary-chassat,Professeur des universités,A
4,Stefan Ambec,"Directeur de recherche, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/stefan-ambec,DR INRAE,A
5,Jean-Pierre Amigues,"Directeur de recherche, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/jean-pierre-amigues,DR INRAE,A
6,Henrik Andersson,"Professeur associé, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/henrik-andersson,Full Professor,A
7,Tiziana Assenza,"Professeure associée d'Economie, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/tiziana-assenza,Associate Professor,A
8,Andrea Attar,"Chargé de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/andrea-attar,CR CNRS,B
9,Emmanuelle Auriol,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/emmanuelle-auriol,Full Professor,A
10,Victoria Barham,Directrice de l'école TSE,Chercheuse TSE,https://www.tse-fr.eu/fr/people/victoria-barham,NaN,NaN
11,Pascal Bégout,Maître de conférences à TSE & Manager IMT-TSE,Chercheur TSE,https://www.tse-fr.eu/fr/people/pascal-begout,Maître de conférences,B
12,Milo Bianchi,"Professeur (TSE-TSM), TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/milo-bianchi,Full Professor,A
13,Adrien Blanchet,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/adrien-blanchet,Maître de conférences,B
14,Matteo Bobba,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/matteo-bobba,NaN,NaN
15,Jérôme Bolte,"Professeur, TSE. Congé sabbatique",Chercheur TSE,https://www.tse-fr.eu/fr/people/jerome-bolte,Full Professor,A
16,Jean-François Bonnefon,"Directeur de recherche, CNRS",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/jean-francois-bonnefon,DR CNRS,A
17,Céline Bonnet,"Directrice de recherche, INRAe",Chercheuse TSE,https://www.tse-fr.eu/fr/people/celine-bonnet,DR INRAE,A
18,Christian Bontemps,"Professeur d'Economie, ENAC & TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/christian-bontemps,Full Professor,A
19,Philippe Bontems,"Directeur de recherche, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/philippe-bontems,DR INRAE,A
20,Zohra Bouamra-Mechemache,"Directrice de recherche en Economie, INRAe",Chercheuse TSE,https://www.tse-fr.eu/fr/people/zohra-bouamra-mechemache,DR INRAE,A
21,Rachid Boumahdi,"Maître de conférences, Université Toulouse Capitole",Chercheur TSE,https://www.tse-fr.eu/fr/people/rachid-boumahdi,Maître de conférences,B
22,Stéphane Caprice,"Chargé de recherche en Economie, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/stephane-caprice,CR INRAE,B
23,Sandrine Casanova,"Maîtresse de conférences, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/sandrine-casanova,Maître de conférences,B
24,Charlotte Cavaillé,"Professeure en science politique, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/charlotte-cavaille,NaN,NaN
25,Catherine Cazals,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/catherine-cazals,Maître de conférences,B
26,Sylvain Chabé-Ferret,"Ingénieur de recherche, INRAe-TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/sylvain-chabe-ferret,Pas clair / à déterminer,Pas clair / à déterminer
27,Daniel L. Chen,"Directeur de recherche, CNRS, en disponibilité",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/daniel-l-chen,DR CNRS,A
28,Frédéric Cherbonnier,"Professeur, Institut d'Etudes Politiques de Toulouse",Chercheur TSE,https://www.tse-fr.eu/fr/people/frederic-cherbonnier,Full Professor,A
29,Julien Chhor,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/julien-chhor,Assistant Professor,B
30,Fabrice Collard,"Directeur de l'école doctorale, Directeur de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/fabrice-collard,DR CNRS,A
31,Jacques Crémer,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/jacques-cremer,Full Professor,A
32,Helmuth Cremer,"Professeur de Sciences Economiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/helmuth-cremer,Full Professor,A
33,Abdelaati Daouia,"Professeur de Mathématiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/abdelaati-daouia,Full Professor,A
34,Charlotte De Cannière,"Assistante professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/charlotte-de-canniere,Assistant Professor,B
35,Philippe De Donder,"Directeur de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/philippe-de-donder,DR CNRS,A
36,Olivier De Groote,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/olivier-de-groote,NaN,NaN
37,Jean-Paul Décamps,"Professeur de Mathématiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/jean-paul-decamps,Professeur des universités,A
38,Maxime Derex,"Chargé de recherche, CNRS",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/maxime-derex,CR CNRS,B
39,Marion Desquilbet,"Chargée de recherche en Economie, INRAe",Chercheuse TSE,https://www.tse-fr.eu/fr/people/marion-desquilbet,CR INRAE,B
40,Roberta Dessi,"Maître de conférences, TSE, en disponibilité",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/roberta-dessi,Maître de conférences,B
41,Alexandre de Cornière,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/alexandre-de-corniere,Full Professor,A
42,Paul Diegert,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/paul-diegert,Assistant Professor,B
43,Isabelle Dubec,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/isabelle-dubec,Maître de conférences,B
44,Pierre Dubois,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/pierre-dubois,Full Professor,A
45,Martial Dupaigne,"Professeur d'Economie, Université Montpellier 3",Chercheur TSE,https://www.tse-fr.eu/fr/people/martial-dupaigne,Full Professor,A
46,Isis Durrmeyer,"Professeure, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/isis-durrmeyer,Full Professor,A
47,Olivier Faugeras,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/olivier-faugeras,Maître de conférences,B
48,Patrick Fève,"Professeur d'Économie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/patrick-feve,Full Professor,A
49,Sébastien Gadat,"Professeur de Mathématiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/sebastien-gadat,Full Professor,A
50,Farid Gasmi,"Professeur d'Economie, Université Toulouse Capitole",Chercheur TSE,https://www.tse-fr.eu/fr/people/farid-gasmi,Professeur des universités,A
51,Eric Gautier,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/eric-gautier,Full Professor,A
52,Victor Gay,"Professeur assistant en Economie, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/victor-gay,Assistant Professor,B
53,Ana Gazmuri,"Professeure assistante, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/ana-gazmuri,Assistant Professor,B
54,Fabien Gensbittel,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/fabien-gensbittel,Maître de conférences,B
55,Bertrand Gobillard,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/bertrand-gobillard,Maître de conférences,B
56,Christian Gollier,Professeur d'économie,Chercheur TSE,https://www.tse-fr.eu/fr/people/christian-gollier,Full Professor,A
57,Renato Gomes,"En disponibilité, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/renato-gomes,DR CNRS / INRAE,A
58,Eugenia Gonzalez-Aguado,"Professeure assistante en Economie, TSE, en disponibilité",Chercheuse TSE,https://www.tse-fr.eu/fr/people/eugenia-gonzalez-aguado,Assistant Professor,B
59,Catarina Goulão,Chargé de recherches en Economie associé (INRAE & TSE),Chercheur TSE,https://www.tse-fr.eu/fr/people/catarina-goulao,CR INRAE,B
60,Christine Grün,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/christine-grun,Maître de conférences,B
61,Christian Hellwig,"Professeur d’Economie, TSE. Congé sabbatique",Chercheur TSE,https://www.tse-fr.eu/fr/people/christian-hellwig,Full Professor,A
62,César Hidalgo,"Professeur, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/cesar-hidalgo,Full Professor,A
63,Marion Hoffman,"Professeur assistant, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/marion-hoffman,Assistant Professor,B
64,Johannes Hörner,"Professeur d'Economie, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/johannes-horner,DR CNRS / INRAE,A
65,Aude Illig,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/aude-illig,Maître de conférences,B
66,Marc Ivaldi,"Directeur d'Etudes à l'Ecole des Hautes Etudes en Sciences Sociales, Toulouse (EHESS)",Chercheur TSE,https://www.tse-fr.eu/fr/people/marc-ivaldi,DR CNRS / INRAE,A
67,Doh-Shin Jeon,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/doh-shin-jeon,Full Professor,A
68,Chuqing Jin,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/chuqing-jin,Assistant Professor,B
69,Koen Jochmans,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/koen-jochmans,Full Professor,A
70,Bruno Jullien,"Directeur de recherches, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/bruno-jullien,DR CNRS,A
71,Pascal Lavergne,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/pascal-lavergne,Professeur des universités,A
72,Eve Leconte,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/eve-leconte,Maître de conférences,B
73,Yassine Lefouili,Professeur d'économie,Chercheur TSE,https://www.tse-fr.eu/fr/people/yassine-lefouili,Full Professor,A
74,Jean-Marie Lozachmeur,"Directeur de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/jean-marie-lozachmeur,DR CNRS,A
75,Thierry Magnac,Directeur Scientifique et Doyen de la Recherche de TSE,Chercheur TSE,https://www.tse-fr.eu/fr/people/thierry-magnac,Full Professor,A
76,Thomas Mariotti,"Directeur de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/thomas-mariotti,DR CNRS,A
77,David Martimort,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/david-martimort,Full Professor,A
78,Christine Maurel,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/christine-maurel,Maître de conférences,B
79,Nour Meddahi,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/nour-meddahi,Full Professor,A
80,Laurent Miclo,"Directeur de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/laurent-miclo,DR CNRS,A
81,Josepa Miquel-Florensa,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/josepa-miquel-florensa,Maître de conférences,B
82,Anouch Missirian,"Chargée de recherche, INRAe",Chercheuse TSE,https://www.tse-fr.eu/fr/people/anouch-missirian,CR INRAE,B
83,Ahmed Ezzeldin Mohamed,"Professeur assistant, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/ahmed-ezzeldin-mohamed,Assistant Professor,B
84,Catherine Molho,"Professeur assistant, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/catherine-molho,Assistant Professor,B
85,Mateo Montenegro,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/mateo-montenegro,Assistant Professor,B
86,Maximilian Müller,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/maximilian-muller,Assistant Professor,B
87,Céline Nauges,"Directeur de Recherche, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/celine-nauges,DR INRAE,A
88,Manh-Hung Nguyen,"Chargé de recherche, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/manh-hung-nguyen,CR INRAE,B
89,Hervé Ossard,Conseiller de la direction de TSE,Chercheur TSE,https://www.tse-fr.eu/fr/people/herve-ossard,DR CNRS / INRAE,A
90,Edouard Pauwels,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/edouard-pauwels,NaN,NaN
91,Isabelle Pechoux,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/isabelle-pechoux,Maître de conférences,B
92,Jorge Peña,"Professeur, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/jorge-pena,NaN,NaN
93,Olivier Perrin,"Maître de conférences, Université Toulouse Capitole",Chercheur TSE,https://www.tse-fr.eu/fr/people/olivier-perrin,Maître de conférences,B
94,François Poinas,"Maître de conférences et Doyen de la Formation, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/francois-poinas,Maître de conférences,B
95,Sébastien Pouget,"Directeur de TSE-P et professeur, Université Toulouse Capitole, TSE-TSM",Chercheur TSE,https://www.tse-fr.eu/fr/people/sebastien-pouget,Full Professor,A
96,Vincent Rebeyrol,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/vincent-rebeyrol,Maître de conférences,B
97,Soenje Reiche,Congé sabbatique : Université de Yale,Chercheur TSE,https://www.tse-fr.eu/fr/people/soenje-reiche,NaN,NaN
98,Jérôme Renault,"Professeur en Mathématiques Appliquées, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/jerome-renault,Full Professor,A
99,Patrick Rey,"Professeur de Sciences Économiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/patrick-rey,Full Professor,A
100,Mathias Reynaert,"Professeur d'économie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/mathias-reynaert,Full Professor,A
101,Arnaud Reynaud,Directeur de l'UMR TSE R,Chercheur TSE,https://www.tse-fr.eu/fr/people/arnaud-reynaud,DR CNRS / INRAE,A
102,Andrew Rhodes,"Professeur, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/andrew-rhodes,Full Professor,A
103,Jean-Charles Rochet,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/jean-charles-rochet,Full Professor,A
104,Anne M. Ruiz,"Professeur en Mathématiques Appliqués, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/anne-m-ruiz,Full Professor,A
105,François Salanié,"Chercheur, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/francois-salanie,DR CNRS / INRAE,A
106,Mohamed Saleh,"Professeur d'Histoire Economique à la LSE, en disponibilité",Chercheur TSE,https://www.tse-fr.eu/fr/people/mohamed-saleh,Professeur des universités,A
107,Anna Sanktjohanser,"Professeure assistante, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/anna-sanktjohanser,Assistant Professor,B
108,Paul Seabright,"Professeur d'Economie, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/paul-seabright,Full Professor,A
109,Sara Shahanaghi,"Professeure assistante, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/sara-shahanaghi,Assistant Professor,B
110,Alex Smolin,"Assistant professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/alex-smolin,Assistant Professor,B
111,Jonathan Stieglitz,"Professeur, TSE",Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/jonathan-stieglitz,Full Professor,A
112,Stéphane Straub,"Economiste à la Banque mondiale, en disponibilité",Chercheur TSE,https://www.tse-fr.eu/fr/people/stephane-straub,Full Professor,A
113,Augustin Tapsoba,"Professeur assistant, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/augustin-tapsoba,Assistant Professor,B
114,Emmanuel Thibault,"Professeur d'Economie, Université de Perpignan",Chercheur TSE,https://www.tse-fr.eu/fr/people/emmanuel-thibault,Professeur des universités,A
115,Jean Tirole,Président honoraire TSE & IAST,Chercheur TSE,https://www.tse-fr.eu/fr/people/jean-tirole,Full Professor,A
116,Nicolas Treich,"Chercheur, INRAe",Chercheur TSE,https://www.tse-fr.eu/fr/people/nicolas-treich,DR CNRS / INRAE,A
117,Karine Van Der Straeten,Directrice Générale de la Fondation Jean-Jacques Laffont - TSE,Chercheur IAST/TSE,https://www.tse-fr.eu/fr/people/karine-van-der-straeten,DR CNRS / INRAE,A
118,Stéphane Villeneuve,"Professeur de Mathématiques, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/stephane-villeneuve,Full Professor,A
119,Ekaterina Voltchkova,"Maître de conférences, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/ekaterina-voltchkova,Maître de conférences,B
120,Vera Zaporozhets,"Chargée de recherche, TSE",Chercheuse TSE,https://www.tse-fr.eu/fr/people/vera-zaporozhets,Pas clair / à déterminer,Pas clair / à déterminer
121,Bruno Ziliotto,"Chargé de recherche, CNRS",Chercheur TSE,https://www.tse-fr.eu/fr/people/bruno-ziliotto,CR CNRS,B

In [153]:
import gender_guesser.detector as gender
d = gender.Detector()

In [154]:
df_merge["first_name"] = df_merge["name"].str.split().str[0]

In [155]:
df_merge["gender_guess"] = df_merge["first_name"].apply(d.get_gender)

In [156]:
def clean_gender(g):
    if g in ["male", "mostly_male"]:
        return "Male"
    if g in ["female", "mostly_female"]:
        return "Female"
    return "Unknown"

df_merge["gender"] = df_merge["gender_guess"].apply(clean_gender)

In [157]:
df_merge["gender"].value_counts()

gender
Male       78
Female     35
Unknown     9
Name: count, dtype: int64

In [165]:
df_merge[df_merge["gender"]=="Unknown"]

,name,appelation_site,role,profile_url,profession,rang,first_name,gender_guess,gender
103,Jean-Charles Rochet,"Professeur d'Economie, TSE",Chercheur TSE,https://www.tse-fr.eu/fr/people/jean-charles-rochet,Full Professor,A,Jean-Charles,unknown,Unknown

In [166]:
gender_manual = {
    "Jean-François": "Male",
    "Jean-Charles": "Male",
    "Abdelaati": "Male",
    "Doh-Shin": "Male",
    "Chuqing": "Male",
    "Josepa": "Male",
    "Anouch": "Female",
    "Manh-Hung": "Male",
    "Soenje": "Female"
}

In [167]:
df_merge.loc[df_merge["gender"] == "Unknown", "gender"] = (
    df_merge.loc[df_merge["gender"] == "Unknown", "first_name"]
    .map(gender_manual)
    .fillna("Unknown")
)

In [168]:
df_merge["gender"].value_counts()

gender
Male      85
Female    37
Name: count, dtype: int64

In [169]:
pd.crosstab(df_merge["gender"], df_merge["rang"])

rang     A   B  Pas clair / à déterminer
gender
Female  11  22                         1
Male    57  23                         1

In [170]:
pd.crosstab(df_merge["profession"], df_merge["gender"])

gender                      Female  Male
profession
Assistant Professor              8     9
Associate Professor              1     1
CR CNRS                          1     2
CR INRAE                         3     2
DR CNRS                          1     8
DR CNRS / INRAE                  1     7
DR INRAE                         3     3
Full Professor                   4    33
Maître de conférences           10    10
Pas clair / à déterminer         1     1
Professeur des universités       1     5

In [171]:
pd.crosstab(
    df_merge["profession"],
    df_merge["gender"],
    normalize="index"
)

gender                        Female      Male
profession
Assistant Professor         0.470588  0.529412
Associate Professor         0.500000  0.500000
CR CNRS                     0.333333  0.666667
CR INRAE                    0.600000  0.400000
DR CNRS                     0.111111  0.888889
DR CNRS / INRAE             0.125000  0.875000
DR INRAE                    0.500000  0.500000
Full Professor              0.108108  0.891892
Maître de conférences       0.500000  0.500000
Pas clair / à déterminer    0.500000  0.500000
Professeur des universités  0.166667  0.833333

# crest

In [103]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://crest.science/faculty/"

response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

people = []

cards = soup.select("div.people")

for card in cards:

    # nom
    fullname = card.select_one("h3.fullname")
    name = fullname.get_text(" ", strip=True) if fullname else None

    # research interests
    interests_tag = card.select_one("div.interests span p")
    interests = interests_tag.get_text(strip=True) if interests_tag else None

    # lien profil
    link_tag = card.select_one("h3.fullname a")
    link = "https://crest.science" + link_tag["href"] if link_tag else None

    people.append({
        "name": name,
        "interests": interests,
        "profile_link": link
    })

df_crest = pd.DataFrame(people)

In [104]:
df_crest

,name,interests,profile_link
0,Marie-Laure ALLAIN,"Antitrust, Vertical Relations, Mergers, Industrial Organization",https://crest.science/user/Marie-Laure-ALLAIN
1,Stéphane AURAY,"Macroeconomics, open macro, trade, labor markets dynamics, operation research and economics of wars.",https://crest.science/user/Stéphane-AURAY
2,Geoffrey BARROWS,"Environmental Economics, International Trade",https://crest.science/user/Geoffrey-BARROWS
3,Suzanne BELLUE,"Macroeconomics, Family, Labor, Development Economics",https://crest.science/user/Suzanne-BELLUE
4,Christian BELZIL,"Microeconometrics, Education, Behavioral Economics",https://crest.science/user/Christian-BELZIL
5,David BOUNIE,"Digital Finance, Digital Economics, Industrial Organization",https://crest.science/user/David-BOUNIE
6,Marc BOURREAU,"Industrial organization, competition policy and regulation, digital economics, and telecommunications.",https://crest.science/user/Marc-BOURREAU
7,Pierre BOYER,Public Economics Political Economics Theory of Organizations Banking Regulation European integration,https://crest.science/user/Pierre-BOYER
8,Victor-Emmanuel BRUNEL,"Non-parametric statistics, Learning Theory, Geometric estimation",https://crest.science/user/Victor-Emmanuel-BRUNEL
9,Cristina BUTUCEA,"Non-parametric statistics, Learning theory, Differential Privacy, Quantum statistics",https://crest.science/user/Cristina-BUTUCEA
10,Olivier CATONI,"Statistical Learning Theory, PAC-Bayes bounds, Statistical models for linguistics",https://crest.science/user/Olivier-CATONI
11,Jean-François CHASSAGNEUX,None,https://crest.science/user/Jean-François-CHASSAGNEUX
12,Béatrice CHERRIER,History of economics,https://crest.science/user/Béatrice-CHERRIER
13,Philippe CHONE,"Health Economics, Industrial Organization, Matching Models",https://crest.science/user/Philippe-CHONE
14,Nicolas CHOPIN,"Bayesian computation, Monte Carlo, Bayesian Statistics, Probablistic Machine learning, time series analysis, hidden Markov models, state-space models",https://crest.science/user/Nicolas-CHOPIN
15,Laurie CIARAMELLA,"Innovation economics, Intellectual Property,Public economics,Innovation policy; Financing of innovation, Markets for technology",https://crest.science/user/Laurie-CIARAMELLA
16,Samuel COAVOUX,"Culture, Audiences, Digital uses, Digital platforms, Consumption",https://crest.science/user/Samuel-COAVOUX
17,Julien COMBE,"Market Design, Matching, Applied Theory",https://crest.science/user/Julien-COMBE
18,Gregory CORCOS,"International Trade, Firm Dynamics, Multinational Firms",https://crest.science/user/Gregory-CORCOS
19,Philippe COULANGEON,None,https://crest.science/user/Philippe-COULANGEON
20,Bruno CREPON,"Econometrics, Labor Economics, Development Economics",https://crest.science/user/Bruno-CREPON
21,Marco CUTURI,"Machine learning, optimal transport",https://crest.science/user/Marco-CUTURI
22,Xavier D'HAULTFOEUILLE,"Econometric Theory, Empirical Industrial Organization",https://crest.science/user/Xavier-D'HAULTFOEUILLE
23,Sébastien DA VEIGA,"Machine learning, Kernel methods, Design of experiments, Uncertainty quantification",https://crest.science/user/Sébastien-DA VEIGA
24,Arnak DALALYAN,"high-dimensional statistics, learning theory, robust statistics, non-parametric statistics, dimension reduction",https://crest.science/user/Arnak-DALALYAN
25,Laurent DAVEZIES,"Econometrics (applied and theoretical), policy evaluation (methodology)",https://crest.science/user/Laurent-DAVEZIES
26,Alexandra DE GENDRE,None,https://crest.science/user/Alexandra-DE GENDRE
27,Federico DI PACE,None,https://crest.science/user/Federico-DI PACE
28,Vincent DIVOL,None,https://crest.science/user/Vincent-DIVOL
29,Roxana DUMITRESCU,None,https://crest.science/user/Roxana-DUMITRESCU
30,Salima EL-KOLEI,"Bayesian Statistics, Monte Carlo Particle Methods, time series analysis, hidden Markov models, state-space models",https://crest.science/user/Salima-EL-KOLEI
31,Marie-Pierre ETIENNE,None,https://crest.science/user/Marie-Pierre-ETIENNE
32,Michele FABI,"Microeconomics, Financial Economics.",https://crest.science/user/Michele-FABI
33,Yameng FAN,None,https://crest.science/user/Yameng-FAN
34,Johann FAOUZI,"Machine learning, open source software, Python programming, time series and signal processing, medical applications",https://crest.science/user/Johann-FAOUZI
35,Jean-David FERMANIAN,"Financial econometrics, risk management",https://crest.science/user/Jean-David-FERMANIAN
36,Christian FRANCQ,"Financial econometrics, Time Series Analysis, Statistics",https://crest.science/user/Christian-FRANCQ
37,Bertrand GARBINTI,"Public Economics, Taxation, Economics of Inequality, Family Economics",https://crest.science/user/Bertrand-GARBINTI
38,Javier GONZALEZ DELGADO,"Selective inference, hypothesis testing, clustering, and statistical methods for real-world problems in biology, particularly structural biology and genetics.",https://crest.science/user/Javier-GONZALEZ DELGADO
39,Olivier GOSSNER,"Game Theory, Information Economics, Insurance and finance regulation",https://crest.science/user/Olivier-GOSSNER
40,Marion GOUSSE,"Labor economics, Family Economics, Economics of Education",https://crest.science/user/Marion-GOUSSE
41,Florian GROSSET-TOUBA,"Development economics, environmental economics, labor economics",https://crest.science/user/Florian-GROSSET-TOUBA
42,Sébastien HERBRETEAU,None,https://crest.science/user/Sébastien-HERBRETEAU
43,Cédric HERZET,"Statistical Learning Theory, Optimization, Operational Research, Inverse Problems",https://crest.science/user/Cédric-HERZET
44,Caroline HILLAIRET,"Mathematical Finance and Actuarial science, cyber risk and long term risks,",https://crest.science/user/Caroline-HILLAIRET
45,Guillaume HOLLARD,"Public and individual decision making, Experimental methods in economics",https://crest.science/user/Guillaume-HOLLARD
46,Thierry KAMIONKA,"Applied microeconomics, labor market, health economics, evaluation of public policies",https://crest.science/user/Thierry-KAMIONKA
47,Azadeh KHALEGHI,"statistical learning theory, nonparametric statistics, information theory, long-memory processes",https://crest.science/user/Azadeh-KHALEGHI
48,Anna KORBA,"Machine Learning, Optimal Transport, Optimisation",https://crest.science/user/Anna-KORBA
49,Yukio KORIYAMA,"Game Theory, Political Economy, Experimental Economics",https://crest.science/user/Yukio-KORIYAMA
50,Fanny LANDAUD,None,https://crest.science/user/Fanny-LANDAUD
51,Elia LAPENTA,Theoretical econometrics,https://crest.science/user/Elia-LAPENTA
52,Frédéric LAVANCIER,"Stochastic processes, spatial statistics, spatial point processes",https://crest.science/user/Frédéric-LAVANCIER
53,Yves LE YAOUANQ,"Behavioral economics, Experimental economics, Game theory",https://crest.science/user/Yves-LE YAOUANQ
54,Matthieu LERASLE,"Mathematical statistics, Statistical learning, Robust methods; matching",https://crest.science/user/Matthieu-LERASLE
55,Marion LEROUTIER,"Environmental Economics, Applied Microeconomics",https://crest.science/user/Marion-LEROUTIER
56,Laurent LINNEMER,"Antitrust, Mergers, Procurement, Industrial Organization",https://crest.science/user/Laurent-LINNEMER
57,Olivier LOISEL,"macroeconomic theory, monetary economics",https://crest.science/user/Olivier-LOISEL
58,Olivier LOPEZ,"Climate related risks, emerging risks, cyber risk, actuarial science, machine learning in insurance, survival analysis",https://crest.science/user/Olivier-LOPEZ
59,Guillaume MAILLARD,None,https://crest.science/user/Guillaume-MAILLARD
60,Clément MALGOUYRES,"Labor Economics, Public Economics, Business Taxation, Trade and the labor market",https://crest.science/user/Clément-MALGOUYRES
61,Franck MALHERBET,"Labor economics, Employment protection, Labor market segmentation, Unemployment Insurance",https://crest.science/user/Franck-MALHERBET
62,Eric MATZNER-LOBER,"Nonparametric estimation : kernel, splines, iterative methods;Machine learning : boosting, IBR ; curve analysis.",https://crest.science/user/Eric-MATZNER-LOBER
63,Jean-Baptiste MICHAU,"Monetary and fiscal policy, secular stagnation, public finance",https://crest.science/user/Jean-Baptiste-MICHAU
64,Jaouad MOURTADA,"Statistical learning theory, High-dimensional statistics",https://crest.science/user/Jaouad-MOURTADA
65,Mohammadreza MOUSAVI-KALAN,"Statistical machine learning, Transfer learning, Domain adaptation, Optimization Theory, Distrusted Computing.",https://crest.science/user/Mohammadreza-MOUSAVI-KALAN
66,Matias NUNEZ,"Political economy, Implementation, Game Theory, Experimental Economics",https://crest.science/user/Matias-NUNEZ
67,Antonio OCELLO,None,https://crest.science/user/Antonio-OCELLO
68,Etienne OLLION,"Sociology, Politics, Digital data, Machine learning, Natural language processing, Computational Social Sciences",https://crest.science/user/Etienne-OLLION
69,Louis PAPE,"Digital economics, Empirical Industrial Organization, Labor Economics",https://crest.science/user/Louis-PAPE
70,Valentin PATILEA,"Functional data analysis, Time Series, Duration models",https://crest.science/user/Valentin-PATILEA
71,Vianney PERCHET,"Machine Learning, Game theory, Eco-ML",https://crest.science/user/Vianney-PERCHET
72,Ivaylo PETEV,"environment, lifestyles attitudes and practices, consumption and spending, discrimination, inequality measures",https://crest.science/user/Ivaylo-PETEV
73,Bertille PICARD,None,https://crest.science/user/Bertille-PICARD
74,Emmanuel PILLIAT,None,https://crest.science/user/Emmanuel-PILLIAT
75,François PORTIER,"Monte Carlo Methods, Statistical Learning, Semiparametric Statistics",https://crest.science/user/François-PORTIER
76,Patrick PRAG,"Health, Wellbeing, Biomarkers, Social Inequality, Social Mobility, Work-Family",https://crest.science/user/Patrick-PRAG
77,Julien PRAT,"Information Economics, Macroeconomics, Labor Economics",https://crest.science/user/Julien-PRAT
78,Roland RATHELOT,labour economics,https://crest.science/user/Roland-RATHELOT
79,Alessandro RIBONI,"Political economy, Macroeconomics",https://crest.science/user/Alessandro-RIBONI
80,Giovanni RICCO,"Macroeconomics, monetary economics, macroeconometrics, time-series econometrics, Bayesian econometrics,",https://crest.science/user/Giovanni-RICCO
81,Christian-Yann ROBERT,"Extreme Value Theory and Statistics, Actuarial Theory and Practice, Statistical Finance, Statistical Learning",https://crest.science/user/Christian-Yann-ROBERT
82,Pauline ROSSI,"Applied microeconomics, development economics, family economics, labor economics",https://crest.science/user/Pauline-ROSSI
83,Enrico RUBOLINO,None,https://crest.science/user/Enrico-RUBOLINO
84,Samuel RUFAT,"Geography, Environment, Urban Studies, Inequalities, Spatial analysis, GIS, Computational Social Sciences",https://crest.science/user/Samuel-RUFAT
85,Adrien SAUMARD,"statistical learning theory, High-dimensional statistics, Stein's method, functional and concentration inequalities",https://crest.science/user/Adrien-SAUMARD
86,Benoît SCHMUTZ-BLOCH,Urban economics,https://crest.science/user/Benoît-SCHMUTZ-BLOCH
87,Sara SIGNORELLI,"Labor Economics, Migration Economics, Innovation",https://crest.science/user/Sara-SIGNORELLI
88,Anna SIMONI,"Machine Learnings, Econometrics, Statistics, Bayesian econometrics/statistics, macro nowcasting",https://crest.science/user/Anna-SIMONI
89,Ludovic STEPHAN,None,https://crest.science/user/Ludovic-STEPHAN
90,Austin STROMME,"Statistical optimal transport, Riemannian optimization, theory of machine learning",https://crest.science/user/Austin-STROMME
91,Yuki TAMURA,"Market Design, Social Choice, Matching Theory",https://crest.science/user/Yuki-TAMURA
92,Peter TANKOV,"Stochastic models in finance, sustainable and environmental finance, energy finance",https://crest.science/user/Peter-TANKOV
93,Emmanuelle TAUGOURDEAU,"Public Economics, Environmental Economics, Applied Microeconomics",https://crest.science/user/Emmanuelle-TAUGOURDEAU
94,Lionel TRUQUET,"Time series analysis, statistics for dependent data, Markov models",https://crest.science/user/Lionel-TRUQUET
95,Alexandre TSYBAKOV,"High-dimensional statistics, non-parametric statistics, statistical learning, stochastic optimization",https://crest.science/user/Alexandre-TSYBAKOV
96,Paola TUBARO,"Digital labour, platform economy, AI value chains, digital inequalities, diffusion of disinformation, network science, organisational network analysis",https://crest.science/user/Paola-TUBARO
97,Arne UHLENDORFF,"Labor economics, Public policy evaluation, Job Search, Subjective Expectations, Structural Econometrics",https://crest.science/user/Arne-UHLENDORFF
98,Clémentine VAN EFFENTERRE,None,https://crest.science/user/Clémentine-VAN EFFENTERRE
99,Myriam VIMOND,"Functional data analysis, Data Depth, Image processing, Random Measures, Semiparametric Inference",https://crest.science/user/Myriam-VIMOND
100,Michael VISSER,"Applied Micro-Econometrics, Industrial Organization",https://crest.science/user/Michael-VISSER
101,Patrick WAELBROECK,None,https://crest.science/user/Patrick-WAELBROECK
102,Lionel WILNER,Economics of social insurance,https://crest.science/user/Lionel-WILNER
103,Ikko YAMANE,"Machine Learning, weakly supervised learning, domain adaptation, multitask learning",https://crest.science/user/Ikko-YAMANE
104,Hesu YOON,"Urban Sociology, Evaluation, Inequality, Race",https://crest.science/user/Hesu-YOON
105,Jean-Michel ZAKOIAN,"Financial Econometrics, Time Series Analysis, Volatility models, Dynamic Risk estimation",https://crest.science/user/Jean-Michel-ZAKOIAN
106,Olivier David ZERBIB,"Sustainable and environmental finance, Theoretical and empirical asset pricing",https://crest.science/user/Olivier David-ZERBIB

In [105]:
def get_profile_text(url):

    r = requests.get(url)
    soup = BeautifulSoup(r.text, "html.parser")

    block = soup.select_one("div.um-name")

    if block:
        return block.get_text(" ", strip=True)

    return None

In [106]:
df_crest["profile_text"] = df_crest["profile_link"].apply(get_profile_text)

KeyboardInterrupt:

In [ ]:
df_crest["profile_text"] = df_crest["profile_text"].str.replace(
    r"^.*?(?=CREST)", "", regex=True
)

In [ ]:
df_crest["profile_text"].value_counts()

profile_text
CREST Permanent Member Economics Personal Website                           16
CREST Permanent Member Full Professor Economics Personal Website            14
CREST Permanent Member CNRS Research Fellow Economics Personal Website      13
CREST Permanent Member Statistics Personal Website                          11
CREST Permanent Member Full Professor Statistics Personal Website           10
CREST Permanent Member Full Professor Finance Personal Website               6
CREST Permanent Member Associate Professor Statistics Personal Website       5
CREST Permanent Member Assistant Professor Economics Personal Website        5
CREST Permanent Member Assistant Professor Statistics Personal Website       4
CREST Permanent Member Associate Professor Economics Personal Website        4
CREST Permanent Member Finance Personal Website                              3
CREST Permanent Member Sociology Personal Website                            3
CREST Permanent Member CNRS Research Fellow Sociology Personal Website       2
CREST Permanent Member Sociology                                             2
CREST Permanent Member Economics                                             1
CREST Permanent Member CNRS Research Fellow Statistics Personal Website      1
CREST Permanent Member Associate Professor Finance Personal Website          1
CREST Permanent Member CNRS Research Director Economics Personal Website     1
CREST Permanent Member Statistics                                            1
CREST Permanent Member Associate Professor Sociology Personal Website        1
Name: count, dtype: int64

In [ ]:
df_crest["position"] = None

In [ ]:
df_crest.loc[
    df_crest["profile_text"].str.contains("full professor", case=False, na=False),
    "position"
] = "Full Professor"

In [ ]:
df_crest.loc[
    df_crest["profile_text"].str.contains("CNRS Research Director", case=False, na=False),
    "position"
] = "DR CNRS / INRAE"

In [ ]:
df_crest.loc[
    df_crest["profile_text"].str.contains("associate professor|Associate", case=False, na=False),
    "position"
] = "Associate Professor"

In [ ]:
df_crest.loc[
    df_crest["profile_text"].str.contains("assistant professor", case=False, na=False),
    "position"
] = "Assistant Professor"

In [ ]:
df_crest["rank"] = None

In [ ]:
df_crest.loc[
    df_crest["position"].isin(["Full Professor","Associate Professor"]),
    "rank"
] = "A"

In [ ]:
df_crest.loc[
    df_crest["position"] == "Assistant Professor",
    "rank"
] = "B"

In [ ]:
len(df_crest[df_crest["position"].notna()])

51

## on s'occupe de ceux qui n'ont pas encore de position

In [ ]:
def get_bio_text(url):

    r = requests.get(url)
    soup = BeautifulSoup(r.text, "html.parser")

    bio = soup.select_one('div[data-key="description"] .um-field-value')

    if bio:
        bio_text = bio.get_text(separator=" ", strip=True)
    else:
        bio_text = None

    return bio_text

In [ ]:
df_crest["bio_text"] = None

mask = df_crest["position"].isna()

df_crest.loc[mask, "bio_text"] = df_crest.loc[mask, "profile_link"].apply(get_bio_text)

In [ ]:
# DR
df_crest.loc[
    df_crest["bio_text"].str.contains(
        "research director|senior research fellow|senior researcher|Senior Resarch fellow|Senior Research",
        case=False, na=False
    ),
    "position"
] = "DR CNRS / INRAE"


# CR
df_crest.loc[
    df_crest["bio_text"].str.contains(
        r"Junior Researcher|chargé de recherche|\bcr\b",
        case=False, na=False
    ),
    "position"
] = "CR CNRS / INRAE"


# Professors seulement si pas CNRS
df_crest.loc[
    df_crest["position"].isna() &
    ~df_crest["profile_text"].str.contains("CNRS|INRAE", case=False, na=False) &
    df_crest["bio_text"].str.contains("full professor", case=False, na=False),
    "position"
] = "Full Professor"


df_crest.loc[
    df_crest["position"].isna() &
    ~df_crest["profile_text"].str.contains("CNRS|INRAE", case=False, na=False) &
    df_crest["bio_text"].str.contains(r"\bassociate\s+professor\b", case=False, na=False),
    "position"
] = "Associate Professor"


df_crest.loc[
    df_crest["position"].isna() &
    ~df_crest["profile_text"].str.contains("CNRS|INRAE", case=False, na=False) &
    df_crest["bio_text"].str.contains("assistant professor", case=False, na=False),
    "position"
] = "Assistant Professor"

In [ ]:
df_crest.loc[
    df_crest["position"].isin(["Full Professor","Associate Professor"]),
    "rank"
] = "A"

df_crest.loc[
    df_crest["position"].isin(["Assistant Professor","CR CNRS / INRAE"]),
    "rank"
] = "B"

df_crest.loc[
    df_crest["position"] == "DR CNRS / INRAE",
    "rank"
] = "A"

In [ ]:
df_crest[df_crest["name"].str.contains("TAUGOURDEAU")]

,name,interests,profile_link,profile_text,position,rank,bio_text
93,Emmanuelle TAUGOURDEAU,"Public Economics, Environmental Economics, App...",https://crest.science/user/Emmanuelle-TAUGOURDEAU,CREST Permanent Member CNRS Research Fellow Ec...,None,None,I am CNRS Research Fellow at CREST since 2017 ...

In [ ]:
df_crest["position"].isna().sum()

np.int64(42)

In [ ]:
df_crest["position"].notna().sum()

np.int64(65)

In [ ]:
df_crest[df_crest["position"].isna()].head()

,name,interests,profile_link,profile_text,position,rank,bio_text
2,Geoffrey BARROWS,"Environmental Economics, International Trade",https://crest.science/user/Geoffrey-BARROWS,CREST Permanent Member CNRS Research Fellow Ec...,None,None,I am a CNRS researcher affiliated at the Ecole...
3,Suzanne BELLUE,"Macroeconomics, Family, Labor, Development Eco...",https://crest.science/user/Suzanne-BELLUE,CREST Permanent Member Economics Personal Website,None,None,None
6,Marc BOURREAU,"Industrial organization, competition policy an...",https://crest.science/user/Marc-BOURREAU,CREST Permanent Member Economics Personal Website,None,None,Marc Bourreau is Professor of Economics at Tel...
10,Olivier CATONI,"Statistical Learning Theory, PAC-Bayes bounds,...",https://crest.science/user/Olivier-CATONI,CREST Permanent Member CNRS Research Fellow St...,None,None,None
12,Béatrice CHERRIER,History of economics,https://crest.science/user/Béatrice-CHERRIER,CREST Permanent Member CNRS Research Fellow Ec...,None,None,I am a historian of economics. I am a CNRS res...

# # récupérer le site web de ceux qu'on a tjs pas

In [ ]:
def get_personal_website(url):

    r = requests.get(url)
    soup = BeautifulSoup(r.text, "html.parser")

    link = soup.find("a", string="Personal Website")

    if link:
        return link["href"]
    
    return None

In [ ]:
def get_site_text(url):

    if pd.isna(url):
        return None

    try:
        headers = {"User-Agent": "Mozilla/5.0"}
        r = requests.get(url, headers=headers, timeout=10)

        soup = BeautifulSoup(r.text, "html.parser")

        text = soup.get_text(separator=" ", strip=True)

        return text.lower()

    except:
        return None

In [ ]:
mask = df_crest["position"].isna()

df_crest.loc[mask, "personal_website"] = df_crest.loc[mask, "profile_link"].apply(get_personal_website)

In [ ]:
df_crest.loc[mask, "site_text"] = df_crest.loc[mask, "personal_website"].apply(get_site_text)

In [ ]:
# DR
df_crest.loc[
    df_crest["position"].isna() &
    df_crest["site_text"].str.contains(
        r"\bresearch director\b|\bdirecteur de recherche\b",
        case=False, na=False
    ),
    "position"
] = "DR CNRS / INRAE"


# CR
df_crest.loc[
    df_crest["position"].isna() &
    df_crest["site_text"].str.contains(
        r"junior researcher|chargé de recherche|\bcr\b",
        case=False, na=False
    ),
    "position"
] = "CR CNRS / INRAE"


# Maître de conférences (PRIORITÉ)
df_crest.loc[
    df_crest["position"].isna() &
    df_crest["site_text"].str.contains(
        r"ma[iî]tre de conf[eé]rences",
        case=False, na=False
    ),
    "position"
] = "Maître de conférences"


# Full Professor
df_crest.loc[
    df_crest["position"].isna() &
    ~df_crest["site_text"].str.contains("cnrs|inrae", case=False, na=False) &
    df_crest["site_text"].str.contains("full professor", case=False, na=False),
    "position"
] = "Full Professor"


# Associate Professor
df_crest.loc[
    df_crest["position"].isna() &
    ~df_crest["site_text"].str.contains("cnrs|inrae", case=False, na=False) &
    df_crest["site_text"].str.contains(r"\bassociate\s+professor\b", case=False, na=False),
    "position"
] = "Associate Professor"


# Assistant Professor
df_crest.loc[
    df_crest["position"].isna() &
    df_crest["site_text"].str.contains(
        r"\bassistant\s+professor\b",
        case=False, na=False
    ),
    "position"
] = "Assistant Professor"

In [ ]:
df_crest.loc[
    df_crest["position"].isin(["Full Professor","Associate Professor","DR CNRS / INRAE"]),
    "rank"
] = "A"

df_crest.loc[
    df_crest["position"].isin(["Assistant Professor","CR CNRS / INRAE"]),
    "rank"
] = "B"

In [ ]:
df_crest["profile_text"].value_counts()

profile_text
CREST Permanent Member Economics Personal Website                           16
CREST Permanent Member Full Professor Economics Personal Website            14
CREST Permanent Member CNRS Research Fellow Economics Personal Website      13
CREST Permanent Member Statistics Personal Website                          11
CREST Permanent Member Full Professor Statistics Personal Website           10
CREST Permanent Member Full Professor Finance Personal Website               6
CREST Permanent Member Associate Professor Statistics Personal Website       5
CREST Permanent Member Assistant Professor Economics Personal Website        5
CREST Permanent Member Assistant Professor Statistics Personal Website       4
CREST Permanent Member Associate Professor Economics Personal Website        4
CREST Permanent Member Finance Personal Website                              3
CREST Permanent Member Sociology Personal Website                            3
CREST Permanent Member CNRS Research Fellow Sociology Personal Website       2
CREST Permanent Member Sociology                                             2
CREST Permanent Member Economics                                             1
CREST Permanent Member CNRS Research Fellow Statistics Personal Website      1
CREST Permanent Member Associate Professor Finance Personal Website          1
CREST Permanent Member CNRS Research Director Economics Personal Website     1
CREST Permanent Member Statistics                                            1
CREST Permanent Member Associate Professor Sociology Personal Website        1
Name: count, dtype: int64

In [ ]:
df_crest = df_crest[~df_crest["profile_text"].str.contains("sociology", case=False, na=False)]

In [ ]:
df_crest = df_crest[~df_crest["profile_text"].str.contains("finance", case=False, na=False)]

In [ ]:
df_crest["position"].isna().sum()

np.int64(16)

### récuparation de ceux qui nous manquent par recherche internet

In [ ]:
df_crest[df_crest["position"].isna()].head()

,name,interests,profile_link,profile_text,position,rank,bio_text,personal_website,site_text
2,Geoffrey BARROWS,"Environmental Economics, International Trade",https://crest.science/user/Geoffrey-BARROWS,CREST Permanent Member CNRS Research Fellow Ec...,None,None,I am a CNRS researcher affiliated at the Ecole...,https://sites.google.com/site/geoffreybarrows/,geoffrey barrows search this site embedded fil...
10,Olivier CATONI,"Statistical Learning Theory, PAC-Bayes bounds,...",https://crest.science/user/Olivier-CATONI,CREST Permanent Member CNRS Research Fellow St...,None,None,None,http://www.crest.fr/pagesperso.php?user=3435,page not found - crest latest news march 8: ce...
12,Béatrice CHERRIER,History of economics,https://crest.science/user/Béatrice-CHERRIER,CREST Permanent Member CNRS Research Fellow Ec...,None,None,I am a historian of economics. I am a CNRS res...,https://beatricecherrier.wordpress.com/about/,about beatrice cherrier – the undercover histo...
26,Alexandra DE GENDRE,None,https://crest.science/user/Alexandra-DE GENDRE,CREST Permanent Member CNRS Research Fellow Ec...,None,None,I am an economist interested in applied microe...,https://adegendre.github.io/,alexandra de gendre alexandra de gendre home r...
38,Javier GONZALEZ DELGADO,"Selective inference, hypothesis testing, clust...",https://crest.science/user/Javier-GONZALEZ DEL...,None,None,None,None,None,None

In [ ]:
pip install ddgs

/opt/python/lib/python3.13/pty.py:95: DeprecationWarning: This process (pid=37805) is multi-threaded, use of forkpty() may lead to deadlocks in the child.
  pid, fd = os.forkpty()

Collecting ddgs
  Downloading ddgs-9.11.2-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: click>=8.1.8 in /opt/python/lib/python3.13/site-packages (from ddgs) (8.3.1)
Requirement already satisfied: primp==1.1.2 in /opt/python/lib/python3.13/site-packages (from ddgs) (1.1.2)
Requirement already satisfied: lxml>=4.9.4 in /opt/python/lib/python3.13/site-packages (from ddgs) (6.0.2)
Downloading ddgs-9.11.2-py3-none-any.whl (43 kB)
Installing collected packages: ddgs
Successfully installed ddgs-9.11.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from ddgs import DDGS

def search_first_result(name):

    query = f"{name} economics professor"

    with DDGS() as ddgs:
        results = list(ddgs.text(query, max_results=10))

    for r in results:
        url = r["href"].lower()

        # exclure complètement certaines sources
        if any(bad in url for bad in [
            "crest.science",
            "linkedin",
            "hec.edu",
            "researchgate",
            "scholar.google",
            "wikipedia",
            ".pdf"
        ]):
            continue

        # privilégier les sites personnels académiques
        if any(domain in url for domain in [
            "github.io",
            "sites.google",
            "personal",
            "faculty",
            "people",
            "staff",
            "telecom-paris",
            "ensae",
            "polytechnique"
        ]):
            return url

    # fallback : premier résultat acceptable
    for r in results:
        url = r["href"].lower()

        if not any(bad in url for bad in [
            "crest.science",
            "linkedin",
            "hec.edu",
            "researchgate",
            "scholar.google",
            "wikipedia",
            ".pdf"
        ]):
            return url

    return None

In [ ]:
import requests
from bs4 import BeautifulSoup

def get_page_text(url):

    try:
        r = requests.get(url, timeout=10)
        soup = BeautifulSoup(r.text, "html.parser")

        text = soup.get_text(" ", strip=True).lower()

        return text

    except:
        return None

In [ ]:
mask = df_crest["position"].isna()

In [ ]:
df_crest.loc[mask, "google_site"] = df_crest.loc[mask, "name"].apply(search_first_result)

In [ ]:
df_crest.loc[mask, "google_text"] = df_crest.loc[mask, "google_site"].apply(get_page_text)

In [ ]:
# DR
df_crest.loc[
    df_crest["position"].isna() &
    df_crest["google_text"].str.contains(
        r"\bresearch director\b|\bdirecteur de recherche\b",
        case=False, na=False
    ),
    "position"
] = "DR CNRS / INRAE"


# CR
df_crest.loc[
    df_crest["position"].isna() &
    df_crest["google_text"].str.contains(
        r"junior researcher|chargé de recherche|\bcr\b",
        case=False, na=False
    ),
    "position"
] = "CR CNRS / INRAE"


# Maître de conférences
df_crest.loc[
    df_crest["position"].isna() &
    df_crest["google_text"].str.contains(
        r"ma[iî]tre de conf[eé]rences",
        case=False, na=False
    ),
    "position"
] = "Maître de conférences"


# Professor (poste actuel)
df_crest.loc[
    df_crest["position"].isna() &
    ~df_crest["site_text"].str.contains(
        r"assistant\s+professor|associate\s+professor",
        case=False, na=False
    ) &
    df_crest["site_text"].str.contains(
        r"\bprofessor\b",
        case=False, na=False
    ),
    "position"
] = "Full Professor"


# Associate Professor
df_crest.loc[
    df_crest["position"].isna() &
    ~df_crest["google_text"].str.contains("cnrs|inrae", case=False, na=False) &
    df_crest["google_text"].str.contains(
        r"\bassociate\s+professor\b",
        case=False, na=False
    ),
    "position"
] = "Associate Professor"


# Assistant Professor
df_crest.loc[
    df_crest["position"].isna() &
    df_crest["google_text"].str.contains(
        r"\bassistant\s+professor\b|\bassistant\s+professorship\b",
        case=False, na=False
    ),
    "position"
] = "Assistant Professor"

In [ ]:
df_crest.loc[mask, ["name", "position", "google_site", "google_text"]]

                          name             position  \
2             Geoffrey BARROWS                 None
10              Olivier CATONI                 None
12           Béatrice CHERRIER                 None
26         Alexandra DE GENDRE                 None
38     Javier GONZALEZ DELGADO                 None
43               Cédric HERZET  Associate Professor
45           Guillaume HOLLARD       Full Professor
50               Fanny LANDAUD                 None
59          Guillaume MAILLARD  Assistant Professor
67              Antonio OCELLO  Assistant Professor
77                 Julien PRAT                 None
80              Giovanni RICCO       Full Professor
83             Enrico RUBOLINO  Assistant Professor
98   Clémentine VAN EFFENTERRE  Assistant Professor
100             Michael VISSER                 None
101         Patrick WAELBROECK                 None

                                                                                              google_site  \
2                                                          https://sites.google.com/site/geoffreybarrows/
10                                          https://researchportal.ip-paris.fr/en/persons/olivier-catoni/
12                                             https://stonecenter.uchicago.edu/people/beatrice-cherrier/
26                                                                           https://adegendre.github.io/
38                                                                             https://jjgecon.github.io/
43                                                                             https://cherzet.github.io/
45                                                          https://sites.google.com/site/webpagehollard/
50                                                        https://sites.google.com/view/fannylandaud/home
59                                                      https://www.normalesup.org/~maillard/main_en.html
67                                                                      https://antonio-ocello.github.io/
77                                                      https://sites.google.com/site/julienpratecon/home
80                                                           https://cepr.org/about/people/giovanni-ricco
83                                                           https://sites.google.com/view/enricorubolino
98                                             https://sites.google.com/site/vaneffenterreclementine/home
100  https://www.calstate.edu/csu-system/faculty-staff/outstanding-faculty/pages/michael-visser-ph-d.aspx
101                                                  https://www.telecom-paris.fr/patrick-waelbroeck?l=en

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  google_text

In [ ]:
df_crest.loc[
    df_crest["position"].isin(["Full Professor","Associate Professor","DR CNRS / INRAE"]),
    "rank"
] = "A"

df_crest.loc[
    df_crest["position"].isin(["Assistant Professor","CR CNRS / INRAE"]),
    "rank"
] = "B"

In [ ]:
len(df_crest[df_crest["position"].isna()])

9

In [ ]:
df_crest["position"].value_counts()

position
Full Professor           28
Assistant Professor      26
Associate Professor      15
DR CNRS / INRAE           8
CR CNRS / INRAE           2
Maître de conférences     1
Name: count, dtype: int64

In [ ]:
df_crest[df_crest["position"] == "Assistant Professor"]

                           name  \
3                Suzanne BELLUE
17                 Julien COMBE
28                Vincent DIVOL
30              Salima EL-KOLEI
32                 Michele FABI
33                   Yameng FAN
34                Johann FAOUZI
41        Florian GROSSET-TOUBA
42         Sébastien HERBRETEAU
48                   Anna KORBA
51                 Elia LAPENTA
55             Marion LEROUTIER
59           Guillaume MAILLARD
64              Jaouad MOURTADA
65   Mohammadreza MOUSAVI-KALAN
67               Antonio OCELLO
69                   Louis PAPE
73              Bertille PICARD
74             Emmanuel PILLIAT
83              Enrico RUBOLINO
87              Sara SIGNORELLI
89              Ludovic STEPHAN
90               Austin STROMME
91                  Yuki TAMURA
98    Clémentine VAN EFFENTERRE
103                 Ikko YAMANE

                                                                                                               interests  \
3                                                                   Macroeconomics, Family, Labor, Development Economics
17                                                                               Market Design, Matching, Applied Theory
28                                                                                                                  None
30     Bayesian Statistics, Monte Carlo Particle Methods, time series analysis, hidden Markov models, state-space models
32                                                                                  Microeconomics, Financial Economics.
33                                                                                                                  None
34   Machine learning, open source software, Python programming, time series and signal processing, medical applications
41                                                       Development economics, environmental economics, labor economics
42                                                                                                                  None
48                                                                     Machine Learning, Optimal Transport, Optimisation
51                                                                                              Theoretical econometrics
55                                                                       Environmental Economics, Applied Microeconomics
59                                                                                                                  None
64                                                              Statistical learning theory, High-dimensional statistics
65        Statistical machine learning, Transfer learning, Domain adaptation, Optimization Theory, Distrusted Computing.
67                                                                                                                  None
69                                                 Digital economics, Empirical Industrial Organization, Labor Economics
73                                                                                                                  None
74                                                                                                                  None
83                                                                                                                  None
87                                                                      Labor Economics, Migration Economics, Innovation
89                                                                                                                  None
90                                    Statistical optimal transport, Riemannian optimization, theory of machine learning
91                                                                         Market Design, Social Choice, Matching Theory
98                                                                                                                  None
103                                  Machine Learning, weakly supervised learning, domain adaptation, multitask learning

                                              profile_link  \
3                https://crest.science/user/Suzanne-BELLUE
17                 https://crest.science/user/Julien-COMBE
28                https://crest.science/user/Vincent-DIVOL
30              https://crest.science/user/Salima-EL-KOLEI
32                 https://crest.science/user/Michele-FABI
33                   https://crest.science/user/Yameng-FAN
34                https://crest.science/user/Johann-FAOUZI
41        https://crest.science/user/Florian-GROSSET-TOUBA
42         https://crest.science/user/Sébastien-HERBRETEAU
48                   https://crest.science/user/Anna-KORBA
51                 https://crest.science/user/Elia-LAPENTA
55             https://crest.science/user/Marion-LEROUTIER
59           https://crest.science/user/Guillaume-MAILLARD
64              https://crest.science/user/Jaouad-MOURTADA
65   https://crest.science/user/Mohammadreza-MOUSAVI-KALAN
67               https://crest.science/user/Antonio-OCELLO
69                   https://crest.science/user/Louis-PAPE
73              https://crest.science/user/Bertille-PICARD
74             https://crest.science/user/Emmanuel-PILLIAT
83              https://crest.science/user/Enrico-RUBOLINO
87              https://crest.science/user/Sara-SIGNORELLI
89              https://crest.science/user/Ludovic-STEPHAN
90               https://crest.science/user/Austin-STROMME
91                  https://crest.science/user/Yuki-TAMURA
98    https://crest.science/user/Clémentine-VAN EFFENTERRE
103                 https://crest.science/user/Ikko-YAMANE

                                                               profile_text  \
3                         CREST Permanent Member Economics Personal Website
17    CREST Permanent Member Assistant Professor Economics Personal Website
28                       CREST Permanent Member Statistics Personal Website
30   CREST Permanent Member Assistant Professor Statistics Personal Website
32    CREST Permanent Member Assistant Professor Economics Personal Website
33                        CREST Permanent Member Economics Personal Website
34                       CREST Permanent Member Statistics Personal Website
41    CREST Permanent Member Assistant Professor Economics Personal Website
42                       CREST Permanent Member Statistics Personal Website
48   CREST Permanent Member Assistant Professor Statistics Personal Website
51    CREST Permanent Member Assistant Professor Economics Personal Website
55                        CREST Permanent Member Economics Personal Website
59                                        CREST Permanent Member Statistics
64   CREST Permanent Member Assistant Professor Statistics Personal Website
65   CREST Permanent Member Assistant Professor Statistics Personal Website
67                                                                     None
69                        CREST Permanent Member Economics Personal Website
73    CREST Permanent Member Assistant Professor Economics Personal Website
74                       CREST Permanent Member Statistics Personal Website
83                        CREST Permanent Member Economics Personal Website
87                        CREST Permanent Member Economics Personal Website
89                       CREST Permanent Member Statistics Personal Website
90                       CREST Permanent Member Statistics Personal Website
91                        CREST Permanent Member Economics Personal Website
98                                                                     None
103                      CREST Permanent Member Statistics Personal Website

                position rank  \
3    Assistant Professor    B
17   Assistant Professor    B
28   Assistant Professor    B
30   Assistant Professor    B
32   Assistant Professor    B
33   Assistant Professor    B
34   Assistant Professor    B
41   Assistant Professor    B
42   Assistant Professor    B
48   Assistant Professor    B
51   Assistant Professor    B
55   Assistant Professor    B
59   Assistant Professor    B
64   Assistant Professor    B
65   Assistant Professor    B
67   Assistant Professor    B
69   Assistant Professor    B
73   Assistant Professor    B
74   Assistant Professor    B
83   Assistant Professor    B
87   Assistant Professor    B
89   Assistant Professor    B
90   Assistant Professor    B
91   Assistant Professor    B
98   Assistant Professor    B
103  Assistant Professor    B

                                                                                                                                                                                                                                                                                                                                                                                                                               bio_text  \
3                                                                                                                                                                                                                                                                                                                                                                                                                                  None
17                                                                                                                                                                                                                                                                                                                                                                                                                                 None
28                                                                                                                                                                                                                                                                                                                                                                                                                                 None
30                                                                                                                                                                                                                                                                                                                                                                                                                                 None
32                                                                                                                                                                                                                                                                                                                                                                                                                                 None
33                                                                                                                                                                                                                                                                                                                                                                                                                                 None
34   Johann Faouzi is an Assistant Professor of Computer Science at École Nationale de la Statistique et de l'Analyse de l'Information (ENSAI). He is a member of Centre de Recherche en Économie et Statistique (CREST). He has a PhD in Computer Science from Sorbonne Université (2020). His research interests include machine learning for time series and signals, as well as for medical applications, and open source software.
41                                                                                                                                                                                                                                                                                                                                                                                                                                 None
42                                                                                                                                                                                                                                                                                                                                                                                                                                 None
48                                                                                                                                                                                                                                                                                                                                                                                                                                 None
51                                                                                                                                                                                                                                                                                                                                                                                                                                 None
55                                                                                                                                                                                                                                                                                                                                                                                                                                 None
59                                                                                                                                                                                                                                 I arrived at ENSAI in September 2024. Before that, I obtained my PhD from Université Paris-Saclay in September 2020 and spent three years at University of Luxembourg as a post-doctoral researcher.
64                                                                                                                                                                                                                                                                                                                                                                                                                                 None
65                                                                                                                                                                                                                                                                                                                                                                                                                                 None
67                                                                                                                                                                                                                                                                                                                                                                                                                                 None
69                                                                                                                                                                                                                                                                                                                                                                                                                                 None
73                                                                                                                                                                                                                                                                                                                                                                                                                                 None
74                                                                                                                                                                                                                                                                                                                                                                                                                                 None
83                                                                                                                                                                                                                                                                                                                                                                                                                                 None
87                                                                                                                                                                                                                                                                                                                                                                                                                                 None
89                                                                                                                                                                                                                                                                                                                                                                                                                                 None
90                                                                                                                                                                                                                                                                                                                                                                                                                                 None
91                                                                                                                                                                                                                                                                                                                                                                                                                                 None
98                                                                                                                                                                                                                                                                                                                                                                                                                                 None

# pse

In [ ]:
import requests
from bs4 import BeautifulSoup

url = "https://www.parisschoolofeconomics.eu/en/people/"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"
}

r = requests.get(url, headers=headers)

soup = BeautifulSoup(r.text, "html.parser")

print(r.status_code)

200

In [ ]:
print("Piketty" in r.text)

False

# lire un html pour les 5 sites

In [ ]:
import requests
from bs4 import BeautifulSoup

url = "https://www.parisschoolofeconomics.eu/personnes/?keyword=&_persons-category-thematics=23143&_persons-category-thematics=23143&_persons-category-thematics=23228&_persons-category-thematics=23222&_persons-category-thematics=23148&_persons-category-thematics=23217&_persons-category-thematics=23203&_persons-category-thematics=23228%2C23222%2C23148%2C23217%2C23203"

headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)
response.encoding = "utf-8"

html = response.text

soup = BeautifulSoup(html, "html.parser")

pretty_html = soup.prettify()

with open("page.html", "w", encoding="utf-8") as f:
    f.write(pretty_html)